/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    cms_admins: CmsAdminAuthOperations;
  };
  blocks: {};
  collections: {
    courses: Course;
    lessons: Lesson;
    resources: Resource;
    media: Media;
    cms_admins: CmsAdmin;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    courses: {
      lessons: 'lessons';
    };
  };
  collectionsSelect: {
    courses: CoursesSelect<false> | CoursesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cms_admins: CmsAdminsSelect<false> | CmsAdminsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: CmsAdmin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CmsAdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Tracks that group lessons into an ordered sequence.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * URL segment. Lowercase, hyphenated. Changing it breaks existing links.
   */
  slug: string;
  /**
   * What kind of track this is. Adding a new type needs a code change plus a database migration — ask an engineer rather than reusing an ill-fitting one.
   */
  trackType: 'beginner-to-intermediate' | '2-week-crash-course';
  /**
   * Shown on the course card. A sentence or two.
   */
  description?: string | null;
  /**
   * Every lesson pointing at this course, read-only here. Sequence comes from each lesson's Order field — set it on the lesson, not here.
   */
  lessons?: {
    docs?: (number | Lesson)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every lesson, from both of the old lesson systems.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  /**
   * The lesson name, e.g. "Lesson 1 V1". Stored as `lesson` in the old grammar data.
   */
  title: string;
  /**
   * URL segment and the key learner progress is recorded against. A database foreign key cascades renames into existing progress rows, but bookmarked lesson URLs still break — rename rarely.
   */
  slug: string;
  /**
   * Which player renders this lesson, and which list it appears in. Step-through lessons play one component per screen at /newlesson/<slug>; flashcard lessons open with a deck and then run their exercises at /lesson/<slug>, and are the only ones pinned to the dashboard map. Pick the family your components come from — mixing families in one lesson will not render.
   */
  format: 'step' | 'flashcard';
  /**
   * Which track this lesson belongs to.
   */
  course?: (number | null) | Course;
  /**
   * Position within the course, ascending. This is what decides which lesson comes next.
   */
  order?: number | null;
  /**
   * Heading shown on the lessons list card. Falls back to the title.
   */
  cardTitle?: string | null;
  /**
   * Shuffle exercises within each generated group when the lesson is rendered. Turn off for lessons where the order teaches something.
   */
  shuffleExercises?: boolean | null;
  /**
   * Ordered — drag to resequence. Convention: one component per exercise. The player renders an exercise as a single screen and there is no composite renderer yet, so a second block in the same exercise will not show. Add another exercise instead.
   */
  exercises?:
    | {
        /**
         * Optional name, for your own navigation. Not shown to learners.
         */
        label?: string | null;
        /**
         * Convention: one component per exercise. The player renders an exercise as a single screen and there is no composite renderer yet, so a second block in the same exercise will not show. Add another exercise instead.
         */
        components: (
          | VideoPageBlock
          | TermsPageBlock
          | GrammarPageBlock
          | ContentPageBlock
          | MatchingExerciseBlock
          | DragAndDropPuzzleBlock
          | TermMediaSeedBlock
          | MatchAudioExerciseBlock
          | PronunciationExerciseBlock
          | InfoBreakBlock
          | LifeUsefulFactBlock
          | ConnectTheDotsBlock
          | MatchAudioLetterBlock
          | VocabularyDragDropBlock
          | FactBreakBlock
          | FlashcardDeckBlock
          | LegacyJsonBlock
        )[];
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Set it and the lesson pins to that prefecture on the dashboard map; leave it empty for lessons that are not tied to a place.
   */
  prefecture?: string | null;
  tags?: string[] | null;
  /**
   * Content revision label carried over from the old data, e.g. "v1".
   */
  version?: string | null;
  /**
   * Shown at the end of the lesson.
   */
  funFact?: string | null;
  /**
   * Learner-facing notes.
   */
  notes?: string | null;
  /**
   * Awarded on completion. Leave the title empty for no award.
   */
  achievement?: {
    title?: string | null;
    xp?: number | null;
  };
  /**
   * The MongoDB `_id` this lesson was imported from. Re-running the import matches on it, and old `/lesson/<ObjectId>` links resolve through it. Do not edit or reuse.
   */
  sourceId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoPageBlock".
 */
export interface VideoPageBlock {
  title: string;
  /**
   * The lesson video. Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  videoUrl?: string | null;
  /**
   * Free-text notes about the video's form, carried over from the source data. Purely descriptive — nothing renders off it.
   */
  videoForm?: string[] | null;
  /**
   * Optional standalone audio for this page (stored as `audioURL` in the old data). Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  audioUrl?: string | null;
  /**
   * Optional sub-heading shown under the title.
   */
  description?: string | null;
  /**
   * Optional body copy shown under the description.
   */
  content?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoPage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TermsPageBlock".
 */
export interface TermsPageBlock {
  title: string;
  /**
   * Free text in the source data ("Flashcard", …), not an enum. Presentation hint only.
   */
  format?: string | null;
  /**
   * The vocabulary introduced on this page, in display order.
   */
  terms?:
    | {
        term: string;
        /**
         * Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
         */
        imageUrl?: string | null;
        /**
         * Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
         */
        audioUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional sub-heading shown under the title.
   */
  description?: string | null;
  /**
   * Optional body copy shown under the description.
   */
  content?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'termsPage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GrammarPageBlock".
 */
export interface GrammarPageBlock {
  title: string;
  grammarPoints?:
    | {
        /**
         * The pattern being taught, e.g. `〜は〜です`.
         */
        pattern: string;
        /**
         * One sentence per entry.
         */
        examples?: string[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional sub-heading shown under the title.
   */
  description?: string | null;
  /**
   * Optional body copy shown under the description.
   */
  content?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'grammarPage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentPageBlock".
 */
export interface ContentPageBlock {
  title: string;
  /**
   * Optional sub-heading shown under the title.
   */
  description?: string | null;
  /**
   * Optional body copy shown under the description.
   */
  content?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contentPage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchingExerciseBlock".
 */
export interface MatchingExerciseBlock {
  instructions: string;
  /**
   * The pairs the learner has to match.
   */
  items?:
    | {
        phrase: string;
        englishTranslation?: string | null;
        /**
         * Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
         */
        audioUrl?: string | null;
        /**
         * Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
         */
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Free-text layout hints from the source data ("audio buttons", "image"). Presentation only.
   */
  rows?: string[] | null;
  /**
   * Author-curated wrong answers. Leave empty to let the player derive distractors from the terms introduced earlier in the lesson.
   */
  dragDropOptions?: string[] | null;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'matchingExercise';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DragAndDropPuzzleBlock".
 */
export interface DragAndDropPuzzleBlock {
  /**
   * The term this puzzle is about. Stored as `_term` in the source data — it is the only identifying field these carried.
   */
  term: string;
  /**
   * The tiles in the order that counts as correct.
   */
  correctSequence: string[];
  /**
   * Every tile offered, including the wrong ones.
   */
  options: string[];
  /**
   * Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  audioUrl?: string | null;
  /**
   * Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  imageUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dragAndDropPuzzle';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TermMediaSeedBlock".
 */
export interface TermMediaSeedBlock {
  /**
   * Stored as `_term` in the source data.
   */
  term: string;
  /**
   * Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  audioUrl?: string | null;
  /**
   * Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  imageUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'termMediaSeed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchAudioExerciseBlock".
 */
export interface MatchAudioExerciseBlock {
  phrase: string;
  /**
   * The clip the learner hears. Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  audioUrl?: string | null;
  /**
   * Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  imageUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'matchAudioExercise';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PronunciationExerciseBlock".
 */
export interface PronunciationExerciseBlock {
  phrase: string;
  /**
   * Longer display text. The player falls back to the phrase if empty.
   */
  transcript?: string | null;
  /**
   * Optional demonstration video. Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  videoUrl?: string | null;
  /**
   * Dedicated reference audio for scoring — NOT the video's audio track. Without it the pronunciation service has nothing to grade against. Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  audioUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pronunciationExercise';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoBreakBlock".
 */
export interface InfoBreakBlock {
  /**
   * Ungraded copy shown between exercises. Some imported bodies are authoring briefs rather than learner-facing text — those need an editorial pass.
   */
  content: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'infoBreak';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LifeUsefulFactBlock".
 */
export interface LifeUsefulFactBlock {
  content: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'lifeUsefulFact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ConnectTheDotsBlock".
 */
export interface ConnectTheDotsBlock {
  /**
   * Stable, human-meaningful id (e.g. `l3_vocab_5_bonus`). Progress and attempt records key off it — changing it detaches existing learner progress.
   */
  exerciseId: string;
  prompt?: string | null;
  /**
   * Every option shown to the learner.
   */
  items: string[];
  /**
   * The subset of `items` that counts as correct. Match them exactly.
   */
  correctAnswers: string[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'connectTheDots';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchAudioLetterBlock".
 */
export interface MatchAudioLetterBlock {
  /**
   * Stable id — see the note on Connect the dots.
   */
  exerciseId: string;
  prompt?: string | null;
  /**
   * The clip the learner hears. Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  audioUrl?: string | null;
  /**
   * Every letter offered.
   */
  items: string[];
  /**
   * A list for historical reasons — every observed record has exactly one entry. Add one unless you know the player handles more.
   */
  correctAnswers: string[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'matchAudioLetter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VocabularyDragDropBlock".
 */
export interface VocabularyDragDropBlock {
  /**
   * Stable id — see the note on Connect the dots.
   */
  exerciseId: string;
  prompt?: string | null;
  /**
   * The tiles offered, including distractors.
   */
  characterBank: string[];
  /**
   * The assembled answer, as one string.
   */
  correctAnswer: string;
  /**
   * Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  audioUrl?: string | null;
  /**
   * Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  imageUrl?: string | null;
  /**
   * Back-compat alias some imported documents still use. Prefer Image URL above; only fill this in if you are matching an existing record. Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
   */
  image?: string | null;
  /**
   * V2+ bonus batch: hiragana tiles with no Japanese caption hint. Harder variant.
   */
  bonus?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'vocabularyDragDrop';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FactBreakBlock".
 */
export interface FactBreakBlock {
  /**
   * Stable id — see the note on Connect the dots.
   */
  exerciseId: string;
  title?: string | null;
  content?: string | null;
  prompt?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'factBreak';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlashcardDeckBlock".
 */
export interface FlashcardDeckBlock {
  /**
   * Optional heading for the deck.
   */
  title?: string | null;
  /**
   * Replaces the old `flashcards` / `flashcardsAudio` parallel arrays — card and audio travel together, so they cannot fall out of alignment.
   */
  cards?:
    | {
        /**
         * The card face, e.g. "あ/ア".
         */
        card: string;
        /**
         * Optional pronunciation for this card. Paste an absolute URL. Existing Cloudinary URLs work as-is; for new files, upload to Media first and paste the resulting URL here.
         */
        audioUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'flashcardDeck';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegacyJsonBlock".
 */
export interface LegacyJsonBlock {
  /**
   * The `type` string the source document carried.
   */
  originalType: string;
  /**
   * The source item, carried across verbatim because the import did not recognise its shape. This renders nothing. Every one of these is a to-do: re-author it as a real block, or delete it.
   */
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'legacyJson';
}
/**
 * Link collections shown on the Resources page, grouped by category.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  /**
   * The section heading on the Resources page.
   */
  category: string;
  /**
   * Shown in this order.
   */
  items?:
    | {
        /**
         * Stable key for this link, unique within the group. Used as the React key.
         */
        itemId: string;
        title: string;
        /**
         * Absolute URL. Opens in a new tab. Optional on purpose: an entry with a title and description but no link yet is a real state the site already handles — it renders as "(No URL)" — and it keeps a planned resource visible as a to-do instead of losing the note.
         */
        url?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The MongoDB `_id` this group was imported from. Used to make re-imports idempotent.
   */
  sourceId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images, audio and video uploaded here. Copy a file's URL into the media field of whichever component needs it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for screen readers. Required for images; leave empty for audio and video.
   */
  alt?: string | null;
  /**
   * Optional visible caption.
   */
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * People who can sign in to this admin. Not learner accounts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_admins".
 */
export interface CmsAdmin {
  id: number;
  /**
   * Display name shown in the admin UI.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms_admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'cms_admins';
        value: number | CmsAdmin;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms_admins';
    value: number | CmsAdmin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms_admins';
    value: number | CmsAdmin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  trackType?: T;
  description?: T;
  lessons?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  format?: T;
  course?: T;
  order?: T;
  cardTitle?: T;
  shuffleExercises?: T;
  exercises?:
    | T
    | {
        label?: T;
        components?:
          | T
          | {
              videoPage?: T | VideoPageBlockSelect<T>;
              termsPage?: T | TermsPageBlockSelect<T>;
              grammarPage?: T | GrammarPageBlockSelect<T>;
              contentPage?: T | ContentPageBlockSelect<T>;
              matchingExercise?: T | MatchingExerciseBlockSelect<T>;
              dragAndDropPuzzle?: T | DragAndDropPuzzleBlockSelect<T>;
              termMediaSeed?: T | TermMediaSeedBlockSelect<T>;
              matchAudioExercise?: T | MatchAudioExerciseBlockSelect<T>;
              pronunciationExercise?: T | PronunciationExerciseBlockSelect<T>;
              infoBreak?: T | InfoBreakBlockSelect<T>;
              lifeUsefulFact?: T | LifeUsefulFactBlockSelect<T>;
              connectTheDots?: T | ConnectTheDotsBlockSelect<T>;
              matchAudioLetter?: T | MatchAudioLetterBlockSelect<T>;
              vocabularyDragDrop?: T | VocabularyDragDropBlockSelect<T>;
              factBreak?: T | FactBreakBlockSelect<T>;
              flashcardDeck?: T | FlashcardDeckBlockSelect<T>;
              legacyJson?: T | LegacyJsonBlockSelect<T>;
            };
        id?: T;
      };
  prefecture?: T;
  tags?: T;
  version?: T;
  funFact?: T;
  notes?: T;
  achievement?:
    | T
    | {
        title?: T;
        xp?: T;
      };
  sourceId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoPageBlock_select".
 */
export interface VideoPageBlockSelect<T extends boolean = true> {
  title?: T;
  videoUrl?: T;
  videoForm?: T;
  audioUrl?: T;
  description?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TermsPageBlock_select".
 */
export interface TermsPageBlockSelect<T extends boolean = true> {
  title?: T;
  format?: T;
  terms?:
    | T
    | {
        term?: T;
        imageUrl?: T;
        audioUrl?: T;
        id?: T;
      };
  description?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GrammarPageBlock_select".
 */
export interface GrammarPageBlockSelect<T extends boolean = true> {
  title?: T;
  grammarPoints?:
    | T
    | {
        pattern?: T;
        examples?: T;
        id?: T;
      };
  description?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentPageBlock_select".
 */
export interface ContentPageBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchingExerciseBlock_select".
 */
export interface MatchingExerciseBlockSelect<T extends boolean = true> {
  instructions?: T;
  items?:
    | T
    | {
        phrase?: T;
        englishTranslation?: T;
        audioUrl?: T;
        imageUrl?: T;
        id?: T;
      };
  rows?: T;
  dragDropOptions?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DragAndDropPuzzleBlock_select".
 */
export interface DragAndDropPuzzleBlockSelect<T extends boolean = true> {
  term?: T;
  correctSequence?: T;
  options?: T;
  audioUrl?: T;
  imageUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TermMediaSeedBlock_select".
 */
export interface TermMediaSeedBlockSelect<T extends boolean = true> {
  term?: T;
  audioUrl?: T;
  imageUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchAudioExerciseBlock_select".
 */
export interface MatchAudioExerciseBlockSelect<T extends boolean = true> {
  phrase?: T;
  audioUrl?: T;
  imageUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PronunciationExerciseBlock_select".
 */
export interface PronunciationExerciseBlockSelect<T extends boolean = true> {
  phrase?: T;
  transcript?: T;
  videoUrl?: T;
  audioUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoBreakBlock_select".
 */
export interface InfoBreakBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LifeUsefulFactBlock_select".
 */
export interface LifeUsefulFactBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ConnectTheDotsBlock_select".
 */
export interface ConnectTheDotsBlockSelect<T extends boolean = true> {
  exerciseId?: T;
  prompt?: T;
  items?: T;
  correctAnswers?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchAudioLetterBlock_select".
 */
export interface MatchAudioLetterBlockSelect<T extends boolean = true> {
  exerciseId?: T;
  prompt?: T;
  audioUrl?: T;
  items?: T;
  correctAnswers?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VocabularyDragDropBlock_select".
 */
export interface VocabularyDragDropBlockSelect<T extends boolean = true> {
  exerciseId?: T;
  prompt?: T;
  characterBank?: T;
  correctAnswer?: T;
  audioUrl?: T;
  imageUrl?: T;
  image?: T;
  bonus?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FactBreakBlock_select".
 */
export interface FactBreakBlockSelect<T extends boolean = true> {
  exerciseId?: T;
  title?: T;
  content?: T;
  prompt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlashcardDeckBlock_select".
 */
export interface FlashcardDeckBlockSelect<T extends boolean = true> {
  title?: T;
  cards?:
    | T
    | {
        card?: T;
        audioUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegacyJsonBlock_select".
 */
export interface LegacyJsonBlockSelect<T extends boolean = true> {
  originalType?: T;
  data?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  category?: T;
  items?:
    | T
    | {
        itemId?: T;
        title?: T;
        url?: T;
        description?: T;
        id?: T;
      };
  sourceId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_admins_select".
 */
export interface CmsAdminsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}