/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    cms_admins: CmsAdminAuthOperations;
  };
  blocks: {};
  collections: {
    courses: Course;
    lessons: Lesson;
    terms: Term;
    resources: Resource;
    media: Media;
    cms_admins: CmsAdmin;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    courses: {
      lessons: 'lessons';
    };
  };
  collectionsSelect: {
    courses: CoursesSelect<false> | CoursesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    terms: TermsSelect<false> | TermsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cms_admins: CmsAdminsSelect<false> | CmsAdminsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: CmsAdmin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CmsAdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Tracks that group lessons into an ordered sequence.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * URL segment. Lowercase, hyphenated. Changing it breaks existing links.
   */
  slug: string;
  /**
   * What kind of track this is. Adding a new type needs a code change plus a database migration — ask an engineer rather than reusing an ill-fitting one.
   */
  trackType: 'beginner-to-intermediate' | '2-week-crash-course';
  /**
   * Shown on the course card. A sentence or two.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Every lesson pointing at this course, read-only here. Sequence comes from each lesson's Order field — set it on the lesson, not here.
   */
  lessons?: {
    docs?: (number | Lesson)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every lesson, from both of the old lesson systems.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  /**
   * The lesson name, e.g. "Lesson 1 V1". Stored as `lesson` in the old grammar data.
   */
  title: string;
  /**
   * URL segment and the key learner progress is recorded against. A database foreign key cascades renames into existing progress rows, but bookmarked lesson URLs still break — rename rarely.
   */
  slug: string;
  /**
   * Which player renders this lesson, and which list it appears in. Step-through lessons play one component per screen at /newlesson/<slug>; flashcard lessons open with a deck and then run their exercises at /lesson/<slug>, and are the only ones pinned to the dashboard map. Pick the family your components come from — mixing families in one lesson will not render.
   */
  format: 'step' | 'flashcard';
  /**
   * Which track this lesson belongs to.
   */
  course?: (number | null) | Course;
  /**
   * Position within the course, ascending. This is what decides which lesson comes next.
   */
  order?: number | null;
  /**
   * Heading shown on the lessons list card. Falls back to the title.
   */
  cardTitle?: string | null;
  /**
   * Shuffle exercises within each generated group when the lesson is rendered. Turn off for lessons where the order teaches something.
   */
  shuffleExercises?: boolean | null;
  /**
   * Ordered — drag to resequence. One exercise is one screen. Blocks from Content and Practice compose onto that screen in order. The seventeen older blocks are being retired — they still render, but one per exercise; a second one becomes its own screen. Prefer the Content and Practice blocks.
   */
  exercises?:
    | {
        /**
         * Optional name, for your own navigation. Not shown to learners.
         */
        label?: string | null;
        /**
         * One exercise is one screen. Blocks from Content and Practice compose onto that screen in order. The seventeen older blocks are being retired — they still render, but one per exercise; a second one becomes its own screen. Prefer the Content and Practice blocks.
         */
        components: (
          | ProseBlock
          | VideoLessonBlock
          | GrammarPointBlock
          | VocabListBlock
          | MediaFigureBlock
          | MatchPairsBlock
          | ListenAndChooseBlock
          | BuildSentenceBlock
          | SpeakAndScoreBlock
          | MultipleChoiceBlock
          | VideoPageBlock
          | TermsPageBlock
          | GrammarPageBlock
          | ContentPageBlock
          | MatchingExerciseBlock
          | DragAndDropPuzzleBlock
          | TermMediaSeedBlock
          | MatchAudioExerciseBlock
          | PronunciationExerciseBlock
          | InfoBreakBlock
          | LifeUsefulFactBlock
          | ConnectTheDotsBlock
          | MatchAudioLetterBlock
          | VocabularyDragDropBlock
          | FactBreakBlock
          | FlashcardDeckBlock
          | LegacyJsonBlock
        )[];
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Set it and the lesson pins to that prefecture on the dashboard map; leave it empty for lessons that are not tied to a place.
   */
  prefecture?: string | null;
  tags?: string[] | null;
  /**
   * Content revision label carried over from the old data, e.g. "v1".
   */
  version?: string | null;
  /**
   * Shown at the end of the lesson.
   */
  funFact?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Learner-facing notes.
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Awarded on completion. Leave the title empty for no award.
   */
  achievement?: {
    title?: string | null;
    xp?: number | null;
  };
  /**
   * The MongoDB `_id` this lesson was imported from. Re-running the import matches on it, and old `/lesson/<ObjectId>` links resolve through it. Do not edit or reuse.
   */
  sourceId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseBlock".
 */
export interface ProseBlock {
  tone: 'page' | 'card' | 'fact' | 'lifeTip';
  /**
   * Optional heading. The fact and tip tones show it in their band.
   */
  title?: string | null;
  /**
   * Use Ruby and Term for furigana; Example sentence for a worked line.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'prose';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoLessonBlock".
 */
export interface VideoLessonBlock {
  title: string;
  /**
   * The lesson video.
   */
  video?: (number | null) | Media;
  /**
   * Optional standalone audio for this screen.
   */
  audio?: (number | null) | Media;
  /**
   * Notes shown under the video.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoLesson';
}
/**
 * Images, audio and video. Upload once here, then pick the file from the media field of whichever component needs it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for screen readers. Required for images; leave empty for audio and video.
   */
  alt?: string | null;
  /**
   * Optional visible caption.
   */
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GrammarPointBlock".
 */
export interface GrammarPointBlock {
  title?: string | null;
  points?:
    | {
        /**
         * The pattern being taught, e.g. 〜は〜です.
         */
        pattern: string;
        /**
         * The explanation. Add Example sentence blocks for worked examples.
         */
        explanation: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'grammarPoint';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VocabListBlock".
 */
export interface VocabListBlock {
  title?: string | null;
  /**
   * Optional copy above the list.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The words introduced here, in order. Their audio and images come with them.
   */
  terms: (number | Term)[];
  /**
   * `format` on the old Terms page was free text ("Flashcard", …) that the renderer guessed at. This is the same decision, made explicitly.
   */
  layout: 'list' | 'flashcards' | 'grid';
  id?: string | null;
  blockName?: string | null;
  blockType: 'vocabList';
}
/**
 * Words, phrases, kana and kanji. Author a term once here and reference it from lessons — its audio, image and readings then follow it everywhere.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms".
 */
export interface Term {
  id: number;
  /**
   * Stable identifier, lowercase. Seeding and re-import match on this, so changing it creates a new term rather than renaming one.
   */
  key: string;
  kind: 'vocab' | 'phrase' | 'kana' | 'kanji';
  /**
   * How this term is labelled in lists and pickers. Derived from the fields below.
   */
  display?: string | null;
  /**
   * The written form — 初めまして, あ, 食べる. Required for kana and kanji. Much of the imported catalogue has only romaji so far; filling this in is the backlog.
   */
  japanese?: string | null;
  /**
   * The katakana counterpart. This is what the old "あ/ア" strings encoded with a slash; how the pair is displayed is now the renderer's decision, not the data's.
   */
  katakana?: string | null;
  /**
   * Kana reading of the written form — はじめまして.
   */
  reading?: string | null;
  /**
   * Filled in automatically from the reading when left empty. Set it by hand to override.
   */
  romaji?: string | null;
  /**
   * The written form split into segments, each with its reading. Leave a segment's reading empty for okurigana and other parts that take no ruby: 食(た)+べる is two segments.
   */
  furigana?:
    | {
        /**
         * The characters.
         */
        base: string;
        /**
         * Their reading, or empty for none.
         */
        ruby?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * English gloss.
   */
  meaning?: string | null;
  partOfSpeech?: ('noun' | 'verb' | 'adjective' | 'adverb' | 'particle' | 'expression') | null;
  jlpt?: ('N5' | 'N4' | 'N3' | 'N2' | 'N1') | null;
  strokes?: number | null;
  /**
   * Stroke-order diagram. Replaces src/data/kanaStrokeOrder.ts, which hardcoded ten of these as media URLs in a TypeScript constant kept in sync with a migration script by hand.
   */
  strokeOrder?: (number | null) | Media;
  /**
   * Pronunciation. Referencing blocks read it from here.
   */
  audio?: (number | null) | Media;
  /**
   * A picture of the thing, for image-choice exercises.
   */
  image?: (number | null) | Media;
  tags?: string[] | null;
  /**
   * Usage notes for the learner — when to use this word and when not to. Reference other terms inline rather than retyping them.
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaFigureBlock".
 */
export interface MediaFigureBlock {
  image?: (number | null) | Media;
  audio?: (number | null) | Media;
  video?: (number | null) | Media;
  /**
   * Shown under the file.
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaFigure';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchPairsBlock".
 */
export interface MatchPairsBlock {
  /**
   * Shown above the exercise. One line.
   */
  instructions: string;
  /**
   * The words to match. Two or more.
   */
  terms: (number | Term)[];
  /**
   * What the two sides are. Hiragana ↔ katakana is what the old "あ/ア" strings encoded with a slash; it reads both scripts off the term now.
   */
  pairing: 'meaning' | 'reading' | 'kana' | 'audio';
  id?: string | null;
  blockName?: string | null;
  blockType: 'matchPairs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListenAndChooseBlock".
 */
export interface ListenAndChooseBlock {
  /**
   * Shown above the exercise. One line.
   */
  instructions?: string | null;
  /**
   * The word the learner hears and has to pick. Its own audio is what plays, so there is no per-exercise audio field to drift from the word it belongs to.
   */
  term: number | Term;
  /**
   * The wrong answers. Leave empty and the player draws them from the words introduced earlier in the lesson.
   */
  distractors?: (number | Term)[] | null;
  answerWith: 'text' | 'image';
  id?: string | null;
  blockName?: string | null;
  blockType: 'listenAndChoose';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BuildSentenceBlock".
 */
export interface BuildSentenceBlock {
  /**
   * Shown above the exercise. One line.
   */
  instructions?: string | null;
  /**
   * The word or phrase being built, when there is one. Supplies the picture and the audio.
   */
  term?: (number | null) | Term;
  /**
   * Every tile offered, including the wrong ones.
   */
  tiles: string[];
  /**
   * The tiles in the order that counts as correct.
   */
  correctSequence: string[];
  tileScript: 'asAuthored' | 'romaji';
  id?: string | null;
  blockName?: string | null;
  blockType: 'buildSentence';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpeakAndScoreBlock".
 */
export interface SpeakAndScoreBlock {
  /**
   * Shown above the exercise. One line.
   */
  instructions?: string | null;
  /**
   * What to say. Its audio is what the recording is graded against — without audio on the term there is nothing to score, which is why this is required.
   */
  term: number | Term;
  /**
   * Optional longer text to show and score against, when the term's own form is not what you want said. Plain text — the scorer reads it as a string.
   */
  transcript?: string | null;
  /**
   * Optional demonstration of the mouth shape.
   */
  video?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'speakAndScore';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MultipleChoiceBlock".
 */
export interface MultipleChoiceBlock {
  question: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  options: {
    label: string;
    /**
     * Exactly one option is the answer.
     */
    isCorrect?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Shown after answering, right or wrong.
   */
  explanation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'multipleChoice';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoPageBlock".
 */
export interface VideoPageBlock {
  title: string;
  /**
   * The lesson video.
   */
  video?: (number | null) | Media;
  /**
   * Free-text notes about the video's form, carried over from the source data. Purely descriptive — nothing renders off it.
   */
  videoForm?: string[] | null;
  /**
   * Optional standalone audio for this page (stored as `audioURL` in the old data).
   */
  audio?: (number | null) | Media;
  /**
   * Optional sub-heading shown under the title. One line, no formatting.
   */
  description?: string | null;
  /**
   * Optional body copy shown under the description.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoPage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TermsPageBlock".
 */
export interface TermsPageBlock {
  title: string;
  /**
   * Free text in the source data ("Flashcard", …), not an enum. Presentation hint only.
   */
  format?: string | null;
  /**
   * The vocabulary introduced on this page, in display order.
   */
  terms?:
    | {
        term: string;
        image?: (number | null) | Media;
        audio?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional sub-heading shown under the title. One line, no formatting.
   */
  description?: string | null;
  /**
   * Optional body copy shown under the description.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'termsPage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GrammarPageBlock".
 */
export interface GrammarPageBlock {
  title: string;
  grammarPoints?:
    | {
        /**
         * The pattern being taught, e.g. `〜は〜です`.
         */
        pattern: string;
        /**
         * One sentence per entry.
         */
        examples?: string[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional sub-heading shown under the title. One line, no formatting.
   */
  description?: string | null;
  /**
   * Optional body copy shown under the description.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'grammarPage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentPageBlock".
 */
export interface ContentPageBlock {
  title: string;
  /**
   * Optional sub-heading shown under the title. One line, no formatting.
   */
  description?: string | null;
  /**
   * Optional body copy shown under the description.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contentPage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchingExerciseBlock".
 */
export interface MatchingExerciseBlock {
  instructions: string;
  /**
   * The pairs the learner has to match.
   */
  items?:
    | {
        phrase: string;
        englishTranslation?: string | null;
        audio?: (number | null) | Media;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Free-text layout hints from the source data ("audio buttons", "image"). Presentation only.
   */
  rows?: string[] | null;
  /**
   * Author-curated wrong answers. Leave empty to let the player derive distractors from the terms introduced earlier in the lesson.
   */
  dragDropOptions?: string[] | null;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'matchingExercise';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DragAndDropPuzzleBlock".
 */
export interface DragAndDropPuzzleBlock {
  /**
   * The term this puzzle is about. Stored as `_term` in the source data — it is the only identifying field these carried.
   */
  term: string;
  /**
   * The tiles in the order that counts as correct.
   */
  correctSequence: string[];
  /**
   * Every tile offered, including the wrong ones.
   */
  options: string[];
  audio?: (number | null) | Media;
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dragAndDropPuzzle';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TermMediaSeedBlock".
 */
export interface TermMediaSeedBlock {
  /**
   * Stored as `_term` in the source data.
   */
  term: string;
  audio?: (number | null) | Media;
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'termMediaSeed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchAudioExerciseBlock".
 */
export interface MatchAudioExerciseBlock {
  phrase: string;
  /**
   * The clip the learner hears.
   */
  audio?: (number | null) | Media;
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'matchAudioExercise';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PronunciationExerciseBlock".
 */
export interface PronunciationExerciseBlock {
  phrase: string;
  /**
   * Longer display text. The player falls back to the phrase if empty.
   */
  transcript?: string | null;
  /**
   * Optional demonstration video.
   */
  video?: (number | null) | Media;
  /**
   * Dedicated reference audio for scoring — NOT the video's audio track. Without it the pronunciation service has nothing to grade against.
   */
  audio?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pronunciationExercise';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoBreakBlock".
 */
export interface InfoBreakBlock {
  /**
   * Ungraded copy shown between exercises. Some imported bodies are authoring briefs rather than learner-facing text — those need an editorial pass.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'infoBreak';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LifeUsefulFactBlock".
 */
export interface LifeUsefulFactBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'lifeUsefulFact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ConnectTheDotsBlock".
 */
export interface ConnectTheDotsBlock {
  /**
   * Stable, human-meaningful id (e.g. `l3_vocab_5_bonus`). Progress and attempt records key off it — changing it detaches existing learner progress.
   */
  exerciseId: string;
  prompt?: string | null;
  /**
   * Every option shown to the learner.
   */
  items: string[];
  /**
   * The subset of `items` that counts as correct. Match them exactly.
   */
  correctAnswers: string[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'connectTheDots';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchAudioLetterBlock".
 */
export interface MatchAudioLetterBlock {
  /**
   * Stable id — see the note on Connect the dots.
   */
  exerciseId: string;
  prompt?: string | null;
  /**
   * The clip the learner hears.
   */
  audio?: (number | null) | Media;
  /**
   * Every letter offered.
   */
  items: string[];
  /**
   * A list for historical reasons — every observed record has exactly one entry. Add one unless you know the player handles more.
   */
  correctAnswers: string[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'matchAudioLetter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VocabularyDragDropBlock".
 */
export interface VocabularyDragDropBlock {
  /**
   * Stable id — see the note on Connect the dots.
   */
  exerciseId: string;
  prompt?: string | null;
  /**
   * The tiles offered, including distractors.
   */
  characterBank: string[];
  /**
   * The assembled answer, as one string.
   */
  correctAnswer: string;
  audio?: (number | null) | Media;
  image?: (number | null) | Media;
  /**
   * V2+ bonus batch: hiragana tiles with no Japanese caption hint. Harder variant.
   */
  bonus?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'vocabularyDragDrop';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FactBreakBlock".
 */
export interface FactBreakBlock {
  /**
   * Stable id — see the note on Connect the dots.
   */
  exerciseId: string;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prompt?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'factBreak';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlashcardDeckBlock".
 */
export interface FlashcardDeckBlock {
  /**
   * Optional heading for the deck.
   */
  title?: string | null;
  /**
   * Replaces the old `flashcards` / `flashcardsAudio` parallel arrays — card and audio travel together, so they cannot fall out of alignment.
   */
  cards?:
    | {
        /**
         * The card face, e.g. "あ/ア".
         */
        card: string;
        /**
         * Optional pronunciation for this card.
         */
        audio?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'flashcardDeck';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegacyJsonBlock".
 */
export interface LegacyJsonBlock {
  /**
   * The `type` string the source document carried.
   */
  originalType: string;
  /**
   * The source item, carried across verbatim because the import did not recognise its shape. This renders nothing. Every one of these is a to-do: re-author it as a real block, or delete it.
   */
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'legacyJson';
}
/**
 * Link collections shown on the Resources page, grouped by category.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  /**
   * The section heading on the Resources page.
   */
  category: string;
  /**
   * Shown in this order.
   */
  items?:
    | {
        /**
         * Stable key for this link, unique within the group. Used as the React key.
         */
        itemId: string;
        title: string;
        /**
         * Absolute URL. Opens in a new tab. Optional on purpose: an entry with a title and description but no link yet is a real state the site already handles — it renders as "(No URL)" — and it keeps a planned resource visible as a to-do instead of losing the note.
         */
        url?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The MongoDB `_id` this group was imported from. Used to make re-imports idempotent.
   */
  sourceId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * People who can sign in to this admin. Not learner accounts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_admins".
 */
export interface CmsAdmin {
  id: number;
  /**
   * Display name shown in the admin UI.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms_admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'terms';
        value: number | Term;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'cms_admins';
        value: number | CmsAdmin;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms_admins';
    value: number | CmsAdmin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms_admins';
    value: number | CmsAdmin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  trackType?: T;
  description?: T;
  lessons?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  format?: T;
  course?: T;
  order?: T;
  cardTitle?: T;
  shuffleExercises?: T;
  exercises?:
    | T
    | {
        label?: T;
        components?:
          | T
          | {
              prose?: T | ProseBlockSelect<T>;
              videoLesson?: T | VideoLessonBlockSelect<T>;
              grammarPoint?: T | GrammarPointBlockSelect<T>;
              vocabList?: T | VocabListBlockSelect<T>;
              mediaFigure?: T | MediaFigureBlockSelect<T>;
              matchPairs?: T | MatchPairsBlockSelect<T>;
              listenAndChoose?: T | ListenAndChooseBlockSelect<T>;
              buildSentence?: T | BuildSentenceBlockSelect<T>;
              speakAndScore?: T | SpeakAndScoreBlockSelect<T>;
              multipleChoice?: T | MultipleChoiceBlockSelect<T>;
              videoPage?: T | VideoPageBlockSelect<T>;
              termsPage?: T | TermsPageBlockSelect<T>;
              grammarPage?: T | GrammarPageBlockSelect<T>;
              contentPage?: T | ContentPageBlockSelect<T>;
              matchingExercise?: T | MatchingExerciseBlockSelect<T>;
              dragAndDropPuzzle?: T | DragAndDropPuzzleBlockSelect<T>;
              termMediaSeed?: T | TermMediaSeedBlockSelect<T>;
              matchAudioExercise?: T | MatchAudioExerciseBlockSelect<T>;
              pronunciationExercise?: T | PronunciationExerciseBlockSelect<T>;
              infoBreak?: T | InfoBreakBlockSelect<T>;
              lifeUsefulFact?: T | LifeUsefulFactBlockSelect<T>;
              connectTheDots?: T | ConnectTheDotsBlockSelect<T>;
              matchAudioLetter?: T | MatchAudioLetterBlockSelect<T>;
              vocabularyDragDrop?: T | VocabularyDragDropBlockSelect<T>;
              factBreak?: T | FactBreakBlockSelect<T>;
              flashcardDeck?: T | FlashcardDeckBlockSelect<T>;
              legacyJson?: T | LegacyJsonBlockSelect<T>;
            };
        id?: T;
      };
  prefecture?: T;
  tags?: T;
  version?: T;
  funFact?: T;
  notes?: T;
  achievement?:
    | T
    | {
        title?: T;
        xp?: T;
      };
  sourceId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseBlock_select".
 */
export interface ProseBlockSelect<T extends boolean = true> {
  tone?: T;
  title?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoLessonBlock_select".
 */
export interface VideoLessonBlockSelect<T extends boolean = true> {
  title?: T;
  video?: T;
  audio?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GrammarPointBlock_select".
 */
export interface GrammarPointBlockSelect<T extends boolean = true> {
  title?: T;
  points?:
    | T
    | {
        pattern?: T;
        explanation?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VocabListBlock_select".
 */
export interface VocabListBlockSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  terms?: T;
  layout?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaFigureBlock_select".
 */
export interface MediaFigureBlockSelect<T extends boolean = true> {
  image?: T;
  audio?: T;
  video?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchPairsBlock_select".
 */
export interface MatchPairsBlockSelect<T extends boolean = true> {
  instructions?: T;
  terms?: T;
  pairing?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListenAndChooseBlock_select".
 */
export interface ListenAndChooseBlockSelect<T extends boolean = true> {
  instructions?: T;
  term?: T;
  distractors?: T;
  answerWith?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BuildSentenceBlock_select".
 */
export interface BuildSentenceBlockSelect<T extends boolean = true> {
  instructions?: T;
  term?: T;
  tiles?: T;
  correctSequence?: T;
  tileScript?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpeakAndScoreBlock_select".
 */
export interface SpeakAndScoreBlockSelect<T extends boolean = true> {
  instructions?: T;
  term?: T;
  transcript?: T;
  video?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MultipleChoiceBlock_select".
 */
export interface MultipleChoiceBlockSelect<T extends boolean = true> {
  question?: T;
  options?:
    | T
    | {
        label?: T;
        isCorrect?: T;
        id?: T;
      };
  explanation?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoPageBlock_select".
 */
export interface VideoPageBlockSelect<T extends boolean = true> {
  title?: T;
  video?: T;
  videoForm?: T;
  audio?: T;
  description?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TermsPageBlock_select".
 */
export interface TermsPageBlockSelect<T extends boolean = true> {
  title?: T;
  format?: T;
  terms?:
    | T
    | {
        term?: T;
        image?: T;
        audio?: T;
        id?: T;
      };
  description?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GrammarPageBlock_select".
 */
export interface GrammarPageBlockSelect<T extends boolean = true> {
  title?: T;
  grammarPoints?:
    | T
    | {
        pattern?: T;
        examples?: T;
        id?: T;
      };
  description?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentPageBlock_select".
 */
export interface ContentPageBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchingExerciseBlock_select".
 */
export interface MatchingExerciseBlockSelect<T extends boolean = true> {
  instructions?: T;
  items?:
    | T
    | {
        phrase?: T;
        englishTranslation?: T;
        audio?: T;
        image?: T;
        id?: T;
      };
  rows?: T;
  dragDropOptions?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DragAndDropPuzzleBlock_select".
 */
export interface DragAndDropPuzzleBlockSelect<T extends boolean = true> {
  term?: T;
  correctSequence?: T;
  options?: T;
  audio?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TermMediaSeedBlock_select".
 */
export interface TermMediaSeedBlockSelect<T extends boolean = true> {
  term?: T;
  audio?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchAudioExerciseBlock_select".
 */
export interface MatchAudioExerciseBlockSelect<T extends boolean = true> {
  phrase?: T;
  audio?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PronunciationExerciseBlock_select".
 */
export interface PronunciationExerciseBlockSelect<T extends boolean = true> {
  phrase?: T;
  transcript?: T;
  video?: T;
  audio?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoBreakBlock_select".
 */
export interface InfoBreakBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LifeUsefulFactBlock_select".
 */
export interface LifeUsefulFactBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ConnectTheDotsBlock_select".
 */
export interface ConnectTheDotsBlockSelect<T extends boolean = true> {
  exerciseId?: T;
  prompt?: T;
  items?: T;
  correctAnswers?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MatchAudioLetterBlock_select".
 */
export interface MatchAudioLetterBlockSelect<T extends boolean = true> {
  exerciseId?: T;
  prompt?: T;
  audio?: T;
  items?: T;
  correctAnswers?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VocabularyDragDropBlock_select".
 */
export interface VocabularyDragDropBlockSelect<T extends boolean = true> {
  exerciseId?: T;
  prompt?: T;
  characterBank?: T;
  correctAnswer?: T;
  audio?: T;
  image?: T;
  bonus?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FactBreakBlock_select".
 */
export interface FactBreakBlockSelect<T extends boolean = true> {
  exerciseId?: T;
  title?: T;
  content?: T;
  prompt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlashcardDeckBlock_select".
 */
export interface FlashcardDeckBlockSelect<T extends boolean = true> {
  title?: T;
  cards?:
    | T
    | {
        card?: T;
        audio?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegacyJsonBlock_select".
 */
export interface LegacyJsonBlockSelect<T extends boolean = true> {
  originalType?: T;
  data?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms_select".
 */
export interface TermsSelect<T extends boolean = true> {
  key?: T;
  kind?: T;
  display?: T;
  japanese?: T;
  katakana?: T;
  reading?: T;
  romaji?: T;
  furigana?:
    | T
    | {
        base?: T;
        ruby?: T;
        id?: T;
      };
  meaning?: T;
  partOfSpeech?: T;
  jlpt?: T;
  strokes?: T;
  strokeOrder?: T;
  audio?: T;
  image?: T;
  tags?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  category?: T;
  items?:
    | T
    | {
        itemId?: T;
        title?: T;
        url?: T;
        description?: T;
        id?: T;
      };
  sourceId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms_admins_select".
 */
export interface CmsAdminsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RubyInlineBlock".
 */
export interface RubyInlineBlock {
  /**
   * The characters the reading sits above — 漢字.
   */
  base: string;
  /**
   * The reading — かんじ.
   */
  ruby: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ruby';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TermRefInlineBlock".
 */
export interface TermRefInlineBlock {
  /**
   * A word from the vocabulary catalogue. Its reading, furigana and audio come with it, so correcting the term corrects every sentence that references it.
   */
  term: number | Term;
  /**
   * Which form of the term to show here. Falls back to the reading and then the romaji for the entries that have no Japanese script yet.
   */
  display: 'furigana' | 'plain' | 'reading' | 'romaji' | 'meaning';
  /**
   * Add a play button after the word, using the term's own pronunciation audio. Nothing renders if the term has no audio.
   */
  showAudio?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'termRef';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutProseBlock".
 */
export interface CalloutProseBlock {
  tone: 'note' | 'tip' | 'warning';
  title?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExampleSentenceProseBlock".
 */
export interface ExampleSentenceProseBlock {
  /**
   * The sentence. Use Ruby for a one-off reading and Term for a word from the catalogue.
   */
  japanese: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  romaji?: string | null;
  english?: string | null;
  /**
   * Someone reading the sentence aloud.
   */
  audio?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'exampleSentence';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}