#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# This repo reads .env.local (gitignored); the library defaults to .env, which
# nothing here uses.
ENV_FILE=".env.local"

banner "Vercel deployment protection — close the Payload bootstrap window"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create the Vercel project"
say "Payload's create-first-user screen is unauthenticated by design: until one"
say "cms_admins record exists, whoever reaches /admin can make themselves a full"
say "CMS admin. We protect the project before it can ever serve that page."
printf '\n'
open_url "https://vercel.com/new"
step "Import Sachi2631/Cornerstone."
step "Framework Preset: Next.js."
step "Root Directory: .  (the repo root, NOT client/)."
step "Do NOT add environment variables yet — those are CUTOVER.md step 3."
step "Click Deploy."
printf '\n'
note "The first build is expected to fail, or to 500 at runtime: the app refuses"
note "to boot without PAYLOAD_SECRET and BETTER_AUTH_SECRET. That is fine, and"
note "wanted — a deployment that cannot boot cannot serve the bootstrap screen."
pause "Press Enter once the project exists (the build outcome does not matter)."
printf '\n'
say "Its dashboard URL is now https://vercel.com/<team>/<project>"
ask VERCEL_TEAM_SLUG "Team (or account) slug from that URL:"
ask VERCEL_PROJECT_NAME "Project name from that URL:"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Turn on Vercel Authentication (Standard Protection)"
open_url "https://vercel.com/${VERCEL_TEAM_SLUG}/${VERCEL_PROJECT_NAME}/settings/deployment-protection"
say "Settings → Deployment Protection, in the Vercel Authentication section:"
step "Check the toggle is ON — new projects often have it on already."
step "Set the scope to 'Standard Protection'."
step "Click Save."
printf '\n'
note "Standard Protection covers every preview URL and the production *.vercel.app"
note "generated URL, leaving only custom production domains public. That is exactly"
note "the surface exposed between now and DNS, and it is on every plan, Hobby"
note "included — no upgrade needed."
printf '\n'
warn "Do not pick 'All Deployments'. It needs Pro, and it would also wall off"
warn "cornerstone.nihongojp.com once DNS is switched, so learners would meet a"
warn "Vercel login instead of the site."
printf '\n'
if ! confirm "Saved, with the scope set to 'Standard Protection'?"; then
  SKIPPED+=("Vercel Authentication / Standard Protection — the bootstrap window is still open")
  warn "Recorded as not done — the check in stage 4 will not pass."
  pause
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Generate a Protection Bypass for Automation secret"
say "Protection has a cost: 'npm run parity <deployment-url>' now meets the auth"
say "wall instead of the app. CUTOVER.md step 3 verifies the deployment before"
say "DNS, so it needs a way through. This secret is that way."
printf '\n'
open_url "https://vercel.com/${VERCEL_TEAM_SLUG}/${VERCEL_PROJECT_NAME}/settings/deployment-protection"
step "Scroll to 'Protection Bypass for Automation'."
step "Add a secret — name it 'parity check' — then copy the generated value."
printf '\n'
note "Automated callers send it as the x-vercel-protection-bypass header."
note "Regenerating it invalidates the old value until you redeploy."
note "Press Enter with nothing pasted to skip; stage 4 works either way."
printf '\n'
ask_secret VERCEL_AUTOMATION_BYPASS_SECRET "Paste the bypass secret (or Enter to skip):"
if [[ -n "$VERCEL_AUTOMATION_BYPASS_SECRET" ]]; then
  write_env VERCEL_AUTOMATION_BYPASS_SECRET "$VERCEL_AUTOMATION_BYPASS_SECRET"
else
  SKIPPED+=("VERCEL_AUTOMATION_BYPASS_SECRET — automated checks against the protected deployment will meet the auth wall")
  warn "skipped — no bypass secret saved"
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Prove the bootstrap screen is unreachable"
say "Vercel → Deployments → the most recent production deployment. Copy its URL."
ask VERCEL_DEPLOYMENT_URL "Deployment URL (https://….vercel.app):"
write_env VERCEL_DEPLOYMENT_URL "$VERCEL_DEPLOYMENT_URL"

admin_url="${VERCEL_DEPLOYMENT_URL%/}/admin"
body=$(mktemp)
trap 'rm -f "$body"' EXIT

while true; do
  printf '\n'
  say "Fetching $admin_url with no credentials…"
  # curl still emits the -w template on failure (as "000 "), so no fallback is
  # needed here — only the non-zero exit has to be swallowed for `set -e`.
  probe=$(curl -sS -o "$body" -w '%{http_code} %{redirect_url}' --max-time 30 "$admin_url" || true)
  http_status="${probe%% *}"
  redirect="${probe#* }"
  printf '\n'
  note "HTTP ${http_status}${redirect:+   → ${redirect}}"
  printf '\n'

  if grep -qi 'create-first-user' "$body" || [[ "$redirect" == *create-first-user* ]]; then
    printf '  %s✗ FAIL%s — Payload is offering first-user creation to the public.\n' "$RED" "$RESET"
    say "Protection is not active on this URL. Go back and redo stage 2."
  elif [[ "$http_status" == "401" || "$redirect" == *vercel.com* ]]; then
    printf '  %s✓ PASS%s — the Vercel auth wall answered, not Payload.\n' "$GREEN" "$RESET"
    break
  else
    printf '  %s✗ FAIL%s — no auth wall on this URL.\n' "$RED" "$RESET"
    warn "Protection intercepts before your app runs, so a protected URL answers"
    warn "401. Anything else — 200, 404, 500 — means the request reached the"
    warn "project unprotected, or nothing is deployed at this URL yet."
  fi

  printf '\n'
  if ! confirm "Fix it in the dashboard and re-check?"; then
    SKIPPED+=("Auth-wall check on $admin_url never passed")
    break
  fi
done

# The window only becomes real once payload.cms_admins exists, which is the
# migration step — so this check is worth repeating there.
SKIPPED+=("Re-run this wizard's check after CUTOVER.md step 5 (migrations): that is when payload.cms_admins first exists and the bootstrap screen becomes genuinely reachable")

finish
