#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

# The two values this wizard produces are consumed by the Next.js app, so they
# belong in the gitignored .env.local — and get printed for the Vercel side.
ENV_FILE=".env.local"

SERVICE_DIR="services/pronunciation"
IMAGE="cornerstone-pronunciation"
SERVICE_NAME="cornerstone-pronunciation"
LOCAL_PORT=5055
LOCAL_CONTAINER="cornerstone-pronunciation-smoke"

# ── Local helpers (authored, not library) ─────────────────────────────────

# ask_with_default KEY "Prompt" DEFAULT — like ask, but Enter takes DEFAULT.
ask_with_default() {
  local key="$1" prompt="$2" default="$3" input
  printf '  %s%s%s %s[Enter = %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$default" "$RESET"
  read -r input || true
  [[ -z "$input" ]] && input="$default"
  printf -v "$key" '%s' "$input"
}

# manual "what" "how" — record something the wizard could not do, so it lands
# in the closing summary instead of being silently lost.
manual() {
  SKIPPED+=("$1 — $2")
  warn "$1"
  note "  do it by hand: $2"
}

# die "why" — stop early; later stages depend on this one having worked.
die() {
  printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"
  exit 1
}

# poll_health URL SECONDS — poll GET <URL>/health until modelReady is true.
poll_health() {
  local url="$1" deadline=$(( SECONDS + $2 )) body=""
  while (( SECONDS < deadline )); do
    body=$(curl -fsS --max-time 10 "$url/health" 2>/dev/null || true)
    if [[ "$body" == *'"modelReady":true'* ]]; then
      printf '  %s✓%s %s/health → %s\n' "$GREEN" "$RESET" "$url" "$body"
      return 0
    fi
    [[ -n "$body" ]] && printf '  %s… %s%s\n' "$DIM" "$body" "$RESET"
    sleep 5
  done
  warn "gave up after $2s waiting for modelReady:true"
  [[ -n "$body" ]] && note "  last response: $body"
  return 1
}

# expect_401 URL SECRET — a POST /check with the wrong secret must be rejected.
expect_401() {
  local code
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 \
    -X POST "$1/check" -H "x-service-secret: $2" 2>/dev/null || echo 000)
  if [[ "$code" == "401" ]]; then
    printf '  %s✓%s wrong secret rejected with 401\n' "$GREEN" "$RESET"
    return 0
  fi
  warn "expected 401 from a mismatched secret, got HTTP $code"
  return 1
}

cleanup_local() { docker rm -f "$LOCAL_CONTAINER" >/dev/null 2>&1 || true; }
trap cleanup_local EXIT

HAVE_GCLOUD=no
SERVICE_URL=""

banner "Pronunciation service — build, verify, deploy (issue #37)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — Docker and disk"
say "The image bakes the wav2vec2 weights in, so it is ~1.5GB and the build"
say "runs a real inference pass. That is deliberate — do not optimise it away."
printf '\n'
[[ -f "$SERVICE_DIR/Dockerfile" ]] \
  || die "run this from the repository root — $SERVICE_DIR/Dockerfile not found"
say "found $SERVICE_DIR/Dockerfile"

command -v docker >/dev/null 2>&1 || die "docker is not installed"
docker info >/dev/null 2>&1 || die "the Docker daemon is not running — start Docker Desktop"
printf '  %s✓%s docker %s, daemon up\n' "$GREEN" "$RESET" "$(docker --version | awk '{print $3}' | tr -d ,)"

command -v curl >/dev/null 2>&1 || die "curl is required for the verification stages"

say "Free space on this disk:"
df -h . | tail -n1 | sed 's/^/    /'
note "The build needs roughly 5GB of headroom for layers plus the final image."
pause "Ready?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Build the image"
say "Building $IMAGE from $SERVICE_DIR on node:24-bookworm-slim."
printf '\n'
say "The build stage runs scripts/prefetch-model.js, which does one real"
say "inference pass over a second of silence. So a clean build already proves"
say "onnxruntime-node's native bindings work — a broken build fails there"
say "rather than on a learner's request."
printf '\n'
warn "This takes a while: ~300MB of weights download and the inference runs."
note "Expect 10-25 minutes on a cold Docker cache."
printf '\n'
if confirm "Start the build?"; then
  if docker build -t "$IMAGE" "$SERVICE_DIR"; then
    printf '\n  %s✓%s built %s\n' "$GREEN" "$RESET" "$IMAGE"
    docker image inspect "$IMAGE" --format '    size: {{.Size}} bytes' 2>/dev/null || true
  else
    die "the image did not build — fix that before going any further"
  fi
else
  docker image inspect "$IMAGE" >/dev/null 2>&1 \
    || die "no existing $IMAGE image to fall back on"
  warn "skipped the build, using the existing $IMAGE image"
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Confirm the native bindings load in the final image"
say "The prefetch pass ran in the BUILD stage. The final stage is a fresh"
say "node:24-bookworm-slim running as USER node, with node_modules copied in —"
say "so the bindings are worth re-checking there. That is what issue #37 asks"
say "for: confirmed loading inside the built image, not just locally."
printf '\n'
if docker run --rm "$IMAGE" \
     node -e "require('onnxruntime-node'); console.log('onnxruntime-node loaded OK as', require('os').userInfo().username)"; then
  printf '  %s✓%s native bindings load in the final image\n' "$GREEN" "$RESET"
else
  die "onnxruntime-node does not load in the final image — the Node 24 ABI bump is not clean"
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The shared secret"
say "The app and the service must hold an IDENTICAL value. The service refuses"
say "to boot without it and 401s on any mismatch — it is the only access"
say "control this service has."
printf '\n'
if confirm "Generate a new secret? (No = paste an existing one)"; then
  PRONUNCIATION_SERVICE_SECRET="$(openssl rand -hex 32)"
  printf '  %s✓ generated%s (32 bytes, hex)\n' "$GREEN" "$RESET"
else
  ask_secret PRONUNCIATION_SERVICE_SECRET "Paste PRONUNCIATION_SERVICE_SECRET:"
fi
[[ -n "${PRONUNCIATION_SERVICE_SECRET:-}" ]] || die "a secret is required — the service will not boot without one"
write_env PRONUNCIATION_SERVICE_SECRET "$PRONUNCIATION_SERVICE_SECRET"
note "Stage 11 prints it again for the Vercel side."
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Smoke-test the image locally"
say "Running the container here first. A native-binding or model-load failure"
say "found now is cheap; found during the cutover window it is not."
printf '\n'
cleanup_local
if docker run -d --name "$LOCAL_CONTAINER" -p "$LOCAL_PORT:$LOCAL_PORT" \
     -e "PRONUNCIATION_SERVICE_SECRET=$PRONUNCIATION_SERVICE_SECRET" \
     -e "PORT=$LOCAL_PORT" "$IMAGE" >/dev/null; then
  say "container started; waiting for the model to load (up to 3 minutes)"
  printf '\n'
  if poll_health "http://localhost:$LOCAL_PORT" 180; then
    expect_401 "http://localhost:$LOCAL_PORT" "definitely-not-the-secret" || true
  else
    warn "the container never reported modelReady:true. Recent logs:"
    docker logs --tail 30 "$LOCAL_CONTAINER" 2>&1 | sed 's/^/    /' || true
    confirm "Continue to the deploy anyway?" || die "stopping — fix the image first"
  fi
else
  warn "could not start the container locally (is port $LOCAL_PORT already in use?)"
  confirm "Continue anyway?" || die "stopping"
fi
cleanup_local
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — CLI, login, project"
if command -v gcloud >/dev/null 2>&1; then
  HAVE_GCLOUD=yes
  say "gcloud is installed"
else
  warn "gcloud is not installed."
  say "Fastest on this Mac (Homebrew):"
  say "    brew install --cask google-cloud-sdk"
  note "The official installer, if you prefer it, is at:"
  note "  https://docs.cloud.google.com/sdk/docs/install-sdk"
  printf '\n'
  pause "Install it in another terminal, then press Enter."
  if command -v gcloud >/dev/null 2>&1; then HAVE_GCLOUD=yes; fi
fi

if [[ "$HAVE_GCLOUD" != yes ]]; then
  manual "gcloud not available" "install the Google Cloud CLI and re-run this wizard"
  die "cannot continue without gcloud"
fi

printf '\n'
if gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | grep -q .; then
  say "authenticated as: $(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | head -n1)"
else
  say "Opening a browser to sign in to Google Cloud."
  gcloud auth login || die "gcloud login failed"
fi

printf '\n'
say "Available projects:"
gcloud projects list --format='table(projectId,name)' 2>/dev/null | sed 's/^/    /' || true
printf '\n'
ask_with_default GCP_PROJECT "Project id to deploy into:" \
  "$(gcloud config get-value project 2>/dev/null || echo '')"
[[ -n "$GCP_PROJECT" ]] || die "a project id is required"
gcloud config set project "$GCP_PROJECT" >/dev/null 2>&1 || die "could not select project $GCP_PROJECT"
printf '  %s✓%s project set to %s\n' "$GREEN" "$RESET" "$GCP_PROJECT"

ask_with_default GCP_REGION "Region:" "us-central1"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — billing and APIs"
say "Cloud Run, Cloud Build and Artifact Registry all need to be enabled, and"
say "the project needs a billing account attached."
printf '\n'
warn "This container is the only recurring cost in the cutover (~\$5-20/mo)."
warn "An always-on instance with CPU always allocated is billed continuously."
printf '\n'
if gcloud billing projects describe "$GCP_PROJECT" \
     --format='value(billingEnabled)' 2>/dev/null | grep -qi true; then
  printf '  %s✓%s billing is enabled on %s\n' "$GREEN" "$RESET" "$GCP_PROJECT"
else
  warn "could not confirm billing is enabled (this check needs the billing API)."
  open_url "https://console.cloud.google.com/billing/linkedaccount?project=$GCP_PROJECT"
  step "Link a billing account to $GCP_PROJECT, then come back."
  pause "Linked? Press Enter."
fi

printf '\n'
say "Enabling run, cloudbuild and artifactregistry APIs (safe to re-run)…"
if gcloud services enable run.googleapis.com cloudbuild.googleapis.com \
     artifactregistry.googleapis.com --project "$GCP_PROJECT"; then
  printf '  %s✓%s APIs enabled\n' "$GREEN" "$RESET"
else
  manual "APIs may not be enabled" \
    "gcloud services enable run.googleapis.com cloudbuild.googleapis.com artifactregistry.googleapis.com"
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Deploy to Cloud Run"
say "Cloud Build builds the image from $SERVICE_DIR/Dockerfile — the same"
say "Dockerfile you just verified — and Cloud Run runs the result."
printf '\n'
say "Settings that are load-bearing, and the usual way this goes wrong:"
step "--memory=2Gi         less will OOM during inference"
step "--min-instances=1    no scale-to-zero; a cold start reloads the model"
step "--no-cpu-throttling  CPU stays allocated so the loaded model stays hot"
step "--allow-unauthenticated  Vercel calls from dynamic IPs, so the shared"
step "                     secret is the access control — and the platform"
step "                     probe has to reach /health"
printf '\n'
note "The secret goes in via a temporary 0600 env-vars file rather than on the"
note "command line, so it stays out of your shell history and out of ps."
printf '\n'
warn "This starts billing an always-on instance."
if confirm "Deploy $SERVICE_NAME to $GCP_PROJECT / $GCP_REGION now?"; then
  ENV_YAML=$(mktemp)
  chmod 600 "$ENV_YAML"
  printf 'PRONUNCIATION_SERVICE_SECRET: %s\n' "$PRONUNCIATION_SERVICE_SECRET" > "$ENV_YAML"
  if gcloud run deploy "$SERVICE_NAME" \
       --source "$SERVICE_DIR" \
       --project "$GCP_PROJECT" \
       --region "$GCP_REGION" \
       --platform managed \
       --port 5055 \
       --memory 2Gi \
       --cpu 2 \
       --min-instances 1 \
       --no-cpu-throttling \
       --timeout 300 \
       --allow-unauthenticated \
       --env-vars-file "$ENV_YAML"; then
    rm -f "$ENV_YAML"
    printf '\n  %s✓%s deployed\n' "$GREEN" "$RESET"
  else
    rm -f "$ENV_YAML"
    manual "Cloud Run deploy failed" "re-run: gcloud run deploy $SERVICE_NAME --source $SERVICE_DIR"
    die "deploy failed — see the Cloud Build log linked above"
  fi
else
  manual "service not deployed" "gcloud run deploy $SERVICE_NAME --source $SERVICE_DIR"
fi

SERVICE_URL=$(gcloud run services describe "$SERVICE_NAME" \
  --project "$GCP_PROJECT" --region "$GCP_REGION" \
  --format='value(status.url)' 2>/dev/null || true)
if [[ -n "$SERVICE_URL" ]]; then
  printf '  %s✓%s service URL: %s\n' "$GREEN" "$RESET" "$SERVICE_URL"
else
  ask SERVICE_URL "Could not read the URL — paste it (https://…, no path):"
fi
printf '\n'
note "Optional, and NOT required by issue #37: to have Cloud Build redeploy on"
note "every push, open the service in the console and use 'Connect to repo'."
note "That installs the Cloud Build GitHub App, which needs ADMIN on"
note "nihongojp/cornerstone — set Source location to $SERVICE_DIR/Dockerfile."
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Verify — /health reports modelReady"
[[ -n "$SERVICE_URL" ]] || die "no service URL to verify against"
say "Polling $SERVICE_URL/health. It is unauthenticated by design, so the"
say "platform probe can reach it. modelReady is false for the first seconds"
say "after boot while the weights load."
printf '\n'
if poll_health "$SERVICE_URL" 300; then
  printf '  %s✓%s the deployed service is ready\n' "$GREEN" "$RESET"
else
  manual "/health did not report modelReady:true" \
    "gcloud run services logs read $SERVICE_NAME --region $GCP_REGION"
  say "Recent logs:"
  gcloud run services logs read "$SERVICE_NAME" --project "$GCP_PROJECT" \
    --region "$GCP_REGION" --limit 30 2>/dev/null | sed 's/^/    /' || true
fi
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Verify — a mismatched secret is rejected"
say "POSTing to /check with a deliberately wrong x-service-secret. A 401 here"
say "is the proof that the shared secret is actually being enforced."
printf '\n'
if expect_401 "$SERVICE_URL" "definitely-not-the-secret"; then
  :
else
  manual "mismatched secret was not rejected with 401" \
    "check PRONUNCIATION_SERVICE_SECRET is set on the Cloud Run service"
fi
printf '\n'
say "And the real secret should NOT 401. A 400 for a missing recording is the"
say "expected answer — it means the secret passed and validation ran:"
REAL_CODE=$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 \
  -X POST "$SERVICE_URL/check" \
  -H "x-service-secret: $PRONUNCIATION_SERVICE_SECRET" 2>/dev/null || echo 000)
if [[ "$REAL_CODE" == "400" ]]; then
  printf '  %s✓%s real secret accepted (HTTP 400 — recording is required)\n' "$GREEN" "$RESET"
elif [[ "$REAL_CODE" == "401" ]]; then
  warn "the real secret was REJECTED — the container holds a different value"
  manual "secret mismatch between .env.local and the container" \
    "redeploy with the same PRONUNCIATION_SERVICE_SECRET"
else
  note "got HTTP $REAL_CODE — not a 401, so the secret passed"
fi
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Hand over to the Vercel setup"
write_env PRONUNCIATION_SERVICE_URL "$SERVICE_URL"
printf '\n'
say "Set these two on the Vercel project, Production environment. They must"
say "match the container exactly. The URL is an ORIGIN with no path — the app"
say "appends /check itself (src/app/(app)/api/pronunciation/check/route.ts)."
printf '\n'
printf '    PRONUNCIATION_SERVICE_URL     %s\n' "$SERVICE_URL"
printf '    PRONUNCIATION_SERVICE_SECRET  %s\n' "$PRONUNCIATION_SERVICE_SECRET"
printf '\n'
open_url "https://vercel.com/dashboard"
step "Cornerstone project → Settings → Environment Variables."
step "Add both, scoped to Production, then redeploy for them to take effect."
manual "PRONUNCIATION_SERVICE_URL and _SECRET on Vercel" \
  "add both to the Vercel project's Production environment variables"
pause "Added them? Press Enter."

finish

note "Issue #37 acceptance, as verified by this run:"
note "  image builds on node:24-bookworm-slim ....... stage 2"
note "  bindings load inside the built image ........ stage 3"
note "  2GB RAM, scale-to-zero disabled ............. stage 8"
note "  secret set on the container ................. stage 8"
note "  /health returns modelReady:true ............. stage 9"
note "  mismatched secret rejected with 401 ......... stage 10"
note "  URL and secret handed over .................. stage 11"
printf '\n'
