#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# This repo reads .env.local (gitignored); the library defaults to .env, which
# nothing here uses.
ENV_FILE=".env.local"

# Set on Vercel for BOTH environments, per CUTOVER.md step 3.
TARGETS=(production preview)

# Never set on Vercel. Airtable and REVALIDATE_SECRET went with #20; MONGODB_URI
# exists only for the local migration script.
FORBIDDEN=(AIRTABLE_API_KEY AIRTABLE_BASE_ID REVALIDATE_SECRET MONGODB_URI)

# The post-pivot list. BLOB_READ_WRITE_TOKEN is set for you when Blob storage is
# added to the project, so it is checked but never pushed from here.
REQUIRED=(
  DATABASE_URL PAYLOAD_SECRET BETTER_AUTH_SECRET BETTER_AUTH_URL
  RESEND_API_KEY EMAIL_FROM PRONUNCIATION_SERVICE_URL PRONUNCIATION_SERVICE_SECRET
)

PUSHED=()   # names successfully pushed to Vercel this run

# ── Local helpers (authored, not library) ─────────────────────────────────

ask_with_default() {
  local key="$1" prompt="$2" default="$3" input
  printf '  %s%s%s %s[Enter = %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$default" "$RESET"
  read -r input || true
  [[ -z "$input" ]] && input="$default"
  printf -v "$key" '%s' "$input"
}

manual() {
  SKIPPED+=("$1 — $2")
  warn "$1"
  note "  do it by hand: $2"
}

die() {
  printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"
  exit 1
}

# vercel_env NAME VALUE [sensitive] — upsert into Production and Preview.
# The value goes in over stdin, never as an argv, so it stays out of ps and out
# of your shell history. --force makes a re-run an update rather than an error.
vercel_env() {
  local name="$1" value="$2" sensitive="${3:-}" target ok=yes flags
  if [[ -z "$value" ]]; then
    manual "$name not set on Vercel (no value captured)" \
      "vercel env add $name production"
    return
  fi
  for target in "${TARGETS[@]}"; do
    flags=(--force -y)
    [[ "$sensitive" == sensitive ]] && flags+=(--sensitive)
    if printf '%s' "$value" | vercel env add "$name" "$target" "${flags[@]}" >/dev/null 2>&1; then
      printf '  %s✓%s %s → %s\n' "$GREEN" "$RESET" "$name" "$target"
    else
      ok=no
      warn "could not set $name for $target"
    fi
  done
  if [[ "$ok" == yes ]]; then
    PUSHED+=("$name")
  else
    manual "$name incomplete on Vercel" "set it in Settings → Environment Variables"
  fi
}

# vercel_env_names TARGET — names currently defined for that environment.
vercel_env_names() {
  vercel env ls "$1" --format json 2>/dev/null \
    | node -e "
        let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{
          try{const j=JSON.parse(s);
            const rows=Array.isArray(j)?j:(j.envs||j.environmentVariables||[]);
            console.log(rows.map(r=>r.key||r.name).filter(Boolean).join('\n'));
          }catch{ }
        });" 2>/dev/null || true
}

# probe PATH — GET against the deployment, carrying the bypass when we have one.
# Echoes "<status> <bytes>".
probe() {
  local path="$1" hdr=()
  [[ -n "${VERCEL_AUTOMATION_BYPASS_SECRET:-}" ]] \
    && hdr=(-H "x-vercel-protection-bypass: $VERCEL_AUTOMATION_BYPASS_SECRET")
  curl -sS -o /tmp/wiz-probe.$$ -w '%{http_code}' --max-time 45 \
    "${hdr[@]}" "${DEPLOY_URL%/}$path" 2>/dev/null || echo 000
}

DEPLOY_URL=""

banner "Vercel project — stand up and deploy to preview (issue #39)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — repo, CLI, prerequisites"
[[ -f package.json && -d src/app ]] \
  || die "run this from the repository root (package.json + src/app not found)"
say "repo root confirmed"

command -v vercel >/dev/null 2>&1 \
  || die "the vercel CLI is not installed — npm i -g vercel, then re-run"
say "vercel CLI $(vercel --version 2>/dev/null | tail -n1)"

command -v curl >/dev/null 2>&1 || die "curl is required by the verification stages"
printf '\n'
say "engines.node in package.json is $(node -p "require('./package.json').engines.node" 2>/dev/null)."
note "That overrides the Vercel project setting, so no dashboard change is"
note "needed — but stage 10 reads the build log to confirm it, because that"
note "assumption has never been tested on this project."
printf '\n'
warn "This ticket is blocked by #36 and #37. Before continuing you need:"
step "the production Neon branch migrated (#36) — otherwise pages that"
step "  prerender content at build time have nothing to read"
step "the pronunciation container live (#37) — its URL and secret go in at"
step "  stage 8"
printf '\n'
confirm "Are #36 and #37 done?" || die "finish those first — this deploy will not verify without them"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Import the project"
say "Next.js preset, root directory '.' — the repo root, NOT client/, which is"
say "the old CRA app and is about to be deleted."
printf '\n'
if confirm "Does the Vercel project already exist? (from the #32 protection wizard)"; then
  say "Good — we will link to it rather than create it."
else
  open_url "https://vercel.com/new"
  step "Import Sachi2631/Cornerstone."
  step "Framework Preset: Next.js."
  step "Root Directory: .   (the repo root, NOT client/)"
  step "Do NOT add environment variables in the import screen — stages 3-8 do"
  step "  that, for Production and Preview together."
  step "Click Deploy."
  printf '\n'
  note "The first build is expected to fail or 500 at runtime: the app refuses"
  note "to boot without PAYLOAD_SECRET and BETTER_AUTH_SECRET. That is wanted —"
  note "a deployment that cannot boot cannot serve Payload's create-first-user"
  note "screen while the bootstrap window is still open (#32)."
  pause "Press Enter once the project exists (the build outcome does not matter)."
fi
printf '\n'
say "Linking this checkout to the project so the CLI knows where to write…"
if vercel link; then
  printf '  %s✓%s linked\n' "$GREEN" "$RESET"
else
  die "vercel link failed — run 'vercel login' and try again"
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "PAYLOAD_SECRET and BETTER_AUTH_SECRET"
say "Both are freshly generated for this environment — never copied from a"
say "developer's .env.local."
printf '\n'
warn "If you already ran the Neon CI wizard (#36) and it GENERATED these,"
warn "reuse those exact values. CI migrates production with PAYLOAD_SECRET,"
warn "and a mismatch means the app boots with a different secret than the"
warn "migration ran under."
printf '\n'
if confirm "Do you already have values from #36 to reuse?"; then
  ask_secret PAYLOAD_SECRET "Paste PAYLOAD_SECRET:"
  ask_secret BETTER_AUTH_SECRET "Paste BETTER_AUTH_SECRET:"
else
  PAYLOAD_SECRET="$(openssl rand -base64 32)"
  BETTER_AUTH_SECRET="$(openssl rand -base64 32)"
  printf '  %s✓ generated both%s\n\n' "$GREEN" "$RESET"
  printf '    PAYLOAD_SECRET       %s\n' "$PAYLOAD_SECRET"
  printf '    BETTER_AUTH_SECRET   %s\n\n' "$BETTER_AUTH_SECRET"
  warn "Record PAYLOAD_SECRET — the #36 CI secret and CUTOVER.md step 1 both"
  warn "need this same value."
fi
[[ -n "${PAYLOAD_SECRET:-}" && -n "${BETTER_AUTH_SECRET:-}" ]] \
  || die "both secrets are required — the app refuses to boot without them"
write_env PAYLOAD_SECRET "$PAYLOAD_SECRET"
write_env BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"
vercel_env PAYLOAD_SECRET "$PAYLOAD_SECRET" sensitive
vercel_env BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET" sensitive
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "DATABASE_URL"
say "The POOLED connection string for the Neon 'production' branch — the same"
say "one #36 set as PRODUCTION_DATABASE_URL. A pooled host contains '-pooler'."
open_url "https://console.neon.tech/app/projects/bold-bar-07861256/branches"
step "Select the 'production' branch."
step "In Connection details, turn ON 'Pooled connection'."
step "Copy the connection string."
ask_secret DATABASE_URL "Paste the pooled production connection string:"
if [[ -n "$DATABASE_URL" && "$DATABASE_URL" != *"-pooler."* ]]; then
  warn "that does not look pooled — a pooled Neon host contains '-pooler'."
  confirm "Use it anyway?" || DATABASE_URL=""
fi
vercel_env DATABASE_URL "$DATABASE_URL" sensitive
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "BETTER_AUTH_URL"
say "The public origin of the app. Sign-in works but sessions do not persist"
say "when this does not match the domain actually being served."
printf '\n'
note "Before DNS this is the Vercel deployment URL; CUTOVER.md step 7 resets it"
note "to the final domain and redeploys. Either is fine now."
ask_with_default BETTER_AUTH_URL "Public origin (https://…, no trailing slash):" \
  "https://cornerstone.nihongojp.com"
vercel_env BETTER_AUTH_URL "$BETTER_AUTH_URL"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Resend — password-reset email"
say "Without these, reset links are logged to the server console instead of"
say "being emailed. That is fine locally and not fine in production."
open_url "https://resend.com/api-keys"
step "Create or copy an API key."
ask_secret RESEND_API_KEY "Paste RESEND_API_KEY:"
printf '\n'
step "EMAIL_FROM must be on a domain verified in Resend, or nothing sends."
ask_with_default EMAIL_FROM "From address:" "noreply@nihongojp.com"
vercel_env RESEND_API_KEY "$RESEND_API_KEY" sensitive
vercel_env EMAIL_FROM "$EMAIL_FROM"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Blob storage — BLOB_READ_WRITE_TOKEN"
say "Blob backs media uploaded through the CMS. Adding the store to the project"
say "sets BLOB_READ_WRITE_TOKEN for you — this wizard never pushes it."
printf '\n'
open_url "https://vercel.com/dashboard/stores"
step "Storage tab → Create → Blob."
step "Connect it to the Cornerstone project."
printf '\n'
note "Without it, admin media uploads fail; the rest of the app is unaffected,"
note "so this is not a reason to block the deploy."
if confirm "Is Blob storage connected to the project?"; then
  printf '  %s✓%s recorded — stage 9 checks the variable actually appeared\n' "$GREEN" "$RESET"
else
  manual "Blob storage not connected — CMS media uploads will fail" \
    "Vercel → Storage → Create → Blob → connect to the project"
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Pronunciation service"
say "Both values come from the container deployed in #37. The URL is an ORIGIN"
say "with no path — the app appends /check itself."
printf '\n'
if [[ -f "$ENV_FILE" ]] && grep -q '^PRONUNCIATION_SERVICE_URL=' "$ENV_FILE"; then
  note "Found values in $ENV_FILE from the #37 wizard; Enter keeps them."
fi
ask PRONUNCIATION_SERVICE_URL "Service origin (https://…):"
ask_secret PRONUNCIATION_SERVICE_SECRET "Shared secret:"
if [[ -n "$PRONUNCIATION_SERVICE_URL" ]]; then
  printf '\n'
  say "Checking the service is actually up before we point the app at it…"
  if curl -fsS --max-time 20 "${PRONUNCIATION_SERVICE_URL%/}/health" 2>/dev/null \
       | grep -q '"modelReady":true'; then
    printf '  %s✓%s /health reports modelReady:true\n' "$GREEN" "$RESET"
  else
    warn "could not confirm modelReady:true at that URL"
    note "  the app will 503 on pronunciation until the container is healthy"
  fi
fi
write_env PRONUNCIATION_SERVICE_URL "$PRONUNCIATION_SERVICE_URL"
write_env PRONUNCIATION_SERVICE_SECRET "$PRONUNCIATION_SERVICE_SECRET"
vercel_env PRONUNCIATION_SERVICE_URL "$PRONUNCIATION_SERVICE_URL"
vercel_env PRONUNCIATION_SERVICE_SECRET "$PRONUNCIATION_SERVICE_SECRET" sensitive
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Audit — the variable list is the post-pivot one"
say "Two assertions: everything required is present in both environments, and"
say "nothing retired is."
printf '\n'
AUDIT_FAILED=no
for target in "${TARGETS[@]}"; do
  printf '  %s%s%s\n' "$BOLD" "$target" "$RESET"
  names=$(vercel_env_names "$target")
  if [[ -z "$names" ]]; then
    warn "  could not read the variable list for $target"
    AUDIT_FAILED=yes
    continue
  fi
  for want in "${REQUIRED[@]}"; do
    if grep -qx "$want" <<<"$names"; then
      printf '    %s✓%s %s\n' "$GREEN" "$RESET" "$want"
    else
      printf '    %s✗%s %s missing\n' "$RED" "$RESET" "$want"
      AUDIT_FAILED=yes
    fi
  done
  if grep -qx "BLOB_READ_WRITE_TOKEN" <<<"$names"; then
    printf '    %s✓%s BLOB_READ_WRITE_TOKEN (set by the Blob integration)\n' "$GREEN" "$RESET"
  else
    printf '    %s·%s BLOB_READ_WRITE_TOKEN absent — CMS media uploads will fail\n' "$YELLOW" "$RESET"
  fi
  for bad in "${FORBIDDEN[@]}"; do
    if grep -qx "$bad" <<<"$names"; then
      printf '    %s✗%s %s must NOT be set here\n' "$RED" "$RESET" "$bad"
      AUDIT_FAILED=yes
      manual "$bad is set on Vercel ($target)" "vercel env rm $bad $target"
    fi
  done
done
printf '\n'
if [[ "$AUDIT_FAILED" == no ]]; then
  printf '  %s✓%s the list matches CUTOVER.md step 3\n' "$GREEN" "$RESET"
else
  warn "the audit did not pass cleanly — see the marks above"
fi
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Deploy, and confirm the build ran Node 24"
say "Environment variables only take effect on a new build, so this deploy is"
say "the first one that can actually boot."
printf '\n'
if confirm "Deploy a preview build now?"; then
  DEPLOY_URL=$(vercel deploy 2>/dev/null | tail -n1 | tr -d '[:space:]')
  if [[ -n "$DEPLOY_URL" ]]; then
    printf '  %s✓%s deployed: %s\n' "$GREEN" "$RESET" "$DEPLOY_URL"
  else
    warn "could not read a deployment URL from the CLI"
  fi
else
  note "Skipping the deploy — paste an existing deployment URL instead."
fi
[[ -n "$DEPLOY_URL" ]] || ask DEPLOY_URL "Deployment URL (https://….vercel.app):"
[[ -n "$DEPLOY_URL" ]] || die "a deployment URL is needed by the remaining stages"
write_env VERCEL_DEPLOYMENT_URL "$DEPLOY_URL"

printf '\n'
say "Reading the build log for the Node version…"
NODE_LINE=$(vercel inspect "$DEPLOY_URL" --logs 2>&1 | grep -iE 'node\.js version|using node' | head -n3 || true)
if [[ -n "$NODE_LINE" ]]; then
  printf '%s\n' "$NODE_LINE" | sed 's/^/    /'
  if grep -qE '(^|[^0-9])24' <<<"$NODE_LINE"; then
    printf '  %s✓%s the build reported Node 24.x — engines.node held\n' "$GREEN" "$RESET"
  else
    warn "the build did NOT report Node 24.x"
    manual "build is not on Node 24" \
      "Vercel → Settings → Build & Deployment → Node.js Version"
  fi
else
  warn "could not find a Node version line in the build log."
  open_url "https://vercel.com/dashboard"
  step "Open this deployment → Building → find 'Node.js Version'."
  confirm "Does the build log say 24.x?" \
    || manual "Node 24 unconfirmed in the build log" "read it in the dashboard"
fi
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Protection — /admin must hit the wall, not Payload"
say "Until a cms_admins row exists, Payload offers first-user creation to"
say "anyone who reaches /admin. Deployment URLs are not secret — they appear in"
say "build notifications and can be enumerated (#32)."
printf '\n'
admin_probe=$(curl -sS -o /tmp/wiz-admin.$$ -w '%{http_code} %{redirect_url}' \
  --max-time 30 "${DEPLOY_URL%/}/admin" 2>/dev/null || true)
admin_status="${admin_probe%% *}"
admin_redirect="${admin_probe#* }"
note "HTTP ${admin_status}${admin_redirect:+   → ${admin_redirect}}"
if grep -qi 'create-first-user' "/tmp/wiz-admin.$$" 2>/dev/null \
   || [[ "$admin_redirect" == *create-first-user* ]]; then
  printf '  %s✗ FAIL%s — Payload is offering first-user creation to the public.\n' "$RED" "$RESET"
  manual "the Payload bootstrap window is OPEN on $DEPLOY_URL" \
    "run scripts/wizard-vercel-protection.sh"
elif [[ "$admin_status" == "401" || "$admin_redirect" == *vercel.com* ]]; then
  printf '  %s✓ PASS%s — the Vercel auth wall answered, not Payload.\n' "$GREEN" "$RESET"
else
  printf '  %s✗ FAIL%s — no auth wall on this URL (HTTP %s).\n' "$RED" "$RESET" "$admin_status"
  manual "deployment protection is not active on $DEPLOY_URL" \
    "run scripts/wizard-vercel-protection.sh"
fi
rm -f "/tmp/wiz-admin.$$"
printf '\n'
say "Protection has a cost: the checks in stage 12 now meet that same wall."
say "The Protection Bypass for Automation secret is the way through."
open_url "https://vercel.com/dashboard"
step "Settings → Deployment Protection → Protection Bypass for Automation."
step "Copy the secret (the #32 wizard may already have saved it)."
ask_secret VERCEL_AUTOMATION_BYPASS_SECRET "Paste the bypass secret (Enter to skip):"
if [[ -n "$VERCEL_AUTOMATION_BYPASS_SECRET" ]]; then
  write_env VERCEL_AUTOMATION_BYPASS_SECRET "$VERCEL_AUTOMATION_BYPASS_SECRET"
else
  warn "no bypass secret — stage 12 will only be able to see the auth wall"
fi
pause

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Verify the preview"
say "Targeted probes, each carrying the bypass header so they reach the app"
say "rather than the protection wall."
printf '\n'

code=$(probe "/")
if [[ "$code" == "200" ]]; then
  printf '  %s✓%s homepage 200\n' "$GREEN" "$RESET"
else
  printf '  %s✗%s homepage returned %s\n' "$RED" "$RESET" "$code"
  manual "the preview homepage does not load" "check the runtime logs in Vercel"
fi

code=$(probe "/resources")
if [[ "$code" == "200" ]] && grep -q "Podcasts" "/tmp/wiz-probe.$$" 2>/dev/null; then
  printf '  %s✓%s /resources 200 and populated\n' "$GREEN" "$RESET"
elif [[ "$code" == "200" ]]; then
  printf '  %s✗%s /resources 200 but EMPTY — an unmigrated database serves\n' "$RED" "$RESET"
  printf '      a 200 with nothing on it, which is exactly this failure.\n'
  manual "/resources renders empty" "run the content migration (CUTOVER.md step 6)"
else
  printf '  %s✗%s /resources returned %s\n' "$RED" "$RESET" "$code"
fi

# 401 = the route is reachable and rejecting an unauthenticated caller, which is
# what it should do. 503 is the failure this criterion is about: the route
# answering before it ever reaches the container, because its env vars are unset.
code=$(probe "/api/pronunciation/check")
case "$code" in
  503) printf '  %s✗%s pronunciation 503 — the app has no service configured\n' "$RED" "$RESET"
       manual "pronunciation endpoint 503s" \
         "PRONUNCIATION_SERVICE_URL/_SECRET missing on Vercel, or the deploy predates them" ;;
  401|400|405) printf '  %s✓%s pronunciation reachable (HTTP %s, not 503)\n' "$GREEN" "$RESET" "$code" ;;
  *)   printf '  %s·%s pronunciation returned %s\n' "$YELLOW" "$RESET" "$code" ;;
esac
rm -f "/tmp/wiz-probe.$$"

printf '\n'
say "Signup is the one thing worth doing by hand — it is the criterion that"
say "matters most and the one a status code cannot prove."
open_url "${DEPLOY_URL%/}/signup"
step "Create an account. You will meet the Vercel auth wall first; sign in"
step "  with your Vercel account, then the app's own signup form loads."
confirm "Did a signup complete?" \
  || manual "learner signup not verified on the preview" "sign up manually on $DEPLOY_URL"
printf '\n'
note "npm run parity <url> covers the routes, the CMS and the bootstrap flag"
note "far more thoroughly than these probes — but it sends no bypass header, so"
note "it cannot reach a protected deployment. Standard Protection leaves custom"
note "production domains public, so the full run happens at CUTOVER.md step 8,"
note "against the real domain, once DNS is switched."
pause

finish

note "Done here. Next in CUTOVER.md: seed the CMS admin (npm run payload:seed-admins),"
note "which closes the bootstrap window for real, then migrate content, then DNS."
printf '\n'
