#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# This repo reads .env.local (gitignored); the library defaults to .env, which
# nothing here uses.
ENV_FILE=".env.local"

# ──────────────────────────────────────────────────────────────────────────
# Local helpers — CUTOVER-specific, built on the library above.
# ──────────────────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

RUN_DIR="out/cutover/$(date +%Y%m%d-%H%M%S)"
ENV_BACKUP="${ENV_FILE}.cutover-backup"
PROD_ENV_ARMED=0
SEED_CAPTURE=""

have() { command -v "$1" >/dev/null 2>&1; }

# ok / bad — one-line verdicts, used by every verification block below.
ok()  { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }
bad() { printf '  %s✗ %s%s\n' "$RED"   "$1" "$RESET"; }

# mask "value" — show enough of a connection string to recognise it, never
# enough to use it. Prints nothing identifying for short values.
mask() {
  local v="$1"
  if [[ ${#v} -le 12 ]]; then printf '%s' "••••••"; else printf '%s…%s' "${v:0:8}" "${v: -6}"; fi
}

# stop_here "why" — the hard gates. The freeze is survivable; a half-imported
# production database read by a DNS switch is not.
stop_here() {
  printf '\n'
  printf '  %s%s■ STOP%s %s\n' "$BOLD" "$RED" "$RESET" "$1"
  say "Nothing after this point should run. DNS is untouched, the old stack is"
  say "still serving, and every step so far is idempotent — fix the cause and"
  say "re-run this wizard from the top."
  printf '\n'
  disarm_production_env
  exit 1
}

# ── .env.local, armed and disarmed ────────────────────────────────────────
#
# Steps 6 and 7 run local scripts against production, and both read
# `.env.local` themselves (`config({ path: ".env.local" })`) before importing
# the Payload config. So for the length of those two stages — and no longer —
# this wizard points `.env.local` at production, which CUTOVER.md otherwise
# forbids outright.
#
# The original file is copied aside first and moved back by an EXIT/INT/TERM
# trap, so a Ctrl-C restores it too. Only a SIGKILL can strand it, which is why
# the backup path is printed on screen while armed.

arm_production_env() {
  [[ "$PROD_ENV_ARMED" == "1" ]] && return 0
  touch "$ENV_FILE"
  cp "$ENV_FILE" "$ENV_BACKUP"
  PROD_ENV_ARMED=1
  local tmp
  tmp=$(mktemp)
  grep -vE '^(DATABASE_URL|PAYLOAD_SECRET|MONGODB_URI)=' "$ENV_FILE" > "$tmp" || true
  {
    printf 'DATABASE_URL=%s\n'   "$PROD_DATABASE_URL"
    printf 'PAYLOAD_SECRET=%s\n' "$PROD_PAYLOAD_SECRET"
    printf 'MONGODB_URI=%s\n'    "$PROD_MONGODB_URI"
  } >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  printf '\n'
  warn "$ENV_FILE now points at PRODUCTION."
  warn "Do not run 'npm run dev', 'db:studio' or any other local command in"
  warn "another terminal until this wizard restores it."
  note "your original file is at $ENV_BACKUP — restore by hand with:"
  note "  mv $ENV_BACKUP $ENV_FILE"
  printf '\n'
}

disarm_production_env() {
  [[ "$PROD_ENV_ARMED" == "1" ]] || return 0
  if [[ -f "$ENV_BACKUP" ]]; then
    mv "$ENV_BACKUP" "$ENV_FILE"
    PROD_ENV_ARMED=0
    printf '  %s✓ restored%s %s from backup — no longer pointing at production\n' \
      "$GREEN" "$RESET" "$ENV_FILE"
  fi
}

# Passwords print exactly once and stage() clears the screen, so the capture
# file is the only copy between the seed run and 1Password. Never leave it.
shred_capture() {
  [[ -n "$SEED_CAPTURE" && -f "$SEED_CAPTURE" ]] || return 0
  rm -f "$SEED_CAPTURE"
  SEED_CAPTURE=""
}

_cleanup() { shred_capture; disarm_production_env; }
trap '_cleanup' EXIT
trap '_cleanup; exit 130' INT TERM

# highwater FILE — the freeze's high-water mark: counts and newest updatedAt
# for the three collections the import reads. Returns non-zero if mongosh
# could not answer.
highwater() {
  mongosh "$PROD_MONGODB_URI" --quiet --eval '
    ["lessons", "newlessons", "Resource"].forEach((c) =>
      print(c, db[c].countDocuments(),
        JSON.stringify(db[c].find({}, {updatedAt: 1}).sort({updatedAt: -1}).limit(1).toArray())))' \
    > "$1" 2>&1
}

# init_state — what /api/cms_admins/init says about the bootstrap window.
# Needs the automation bypass, because Standard Protection still covers the
# *.vercel.app URL until DNS.
init_state() {
  [[ -n "${VERCEL_DEPLOYMENT_URL:-}" ]] || { printf 'no-deployment-url'; return; }
  curl -sS --max-time 30 \
    -H "x-vercel-protection-bypass: ${VERCEL_AUTOMATION_BYPASS_SECRET:-}" \
    "${VERCEL_DEPLOYMENT_URL%/}/api/cms_admins/init" 2>/dev/null || printf 'request-failed'
}

banner "The production data run — freeze, migrate, seed, import (#40)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — is this the run, and can this machine do it?"
say "This is CUTOVER.md steps 4 through 7, in one sitting. It opens a content"
say "freeze and closes when Sachi can author again. It does NOT touch DNS —"
say "the old stack keeps serving throughout, so rollback stays free."
printf '\n'

mkdir -p "$RUN_DIR"
note "run artifacts (logs, high-water marks): $RUN_DIR"
printf '\n'

preflight_failed=0
node_major="$( (node -v 2>/dev/null || echo v0) | sed 's/^v//; s/\..*//')"
if [[ "$node_major" -ge 24 ]]; then
  ok "node $(node -v) — payload:* commands need 24 (.nvmrc)"
else
  bad "node $(node -v 2>/dev/null || echo 'not found') — every payload:* command dies with ERR_VM_MODULE_LINK_FAILURE below 24"
  say "  fix: nvm use   (.nvmrc pins 24)"
  preflight_failed=1
fi

for tool in npm gh psql mongosh curl; do
  if have "$tool"; then ok "$tool"; else bad "$tool — not on PATH"; preflight_failed=1; fi
done

if have gh && gh auth status >/dev/null 2>&1; then
  ok "gh is authenticated — stage 5 dispatches the migration workflow"
else
  bad "gh is not authenticated (gh auth login) — stage 5 cannot dispatch the workflow"
  preflight_failed=1
fi

if [[ -f .github/workflows/migrate-production.yml ]]; then
  ok "migrate-production.yml is present (#36)"
else
  bad "migrate-production.yml is missing — production migrations have no gated path"
  preflight_failed=1
fi

printf '\n'
say "CUTOVER.md's own ordering, read live rather than assumed (#32 may have"
say "moved the seed ahead of the import):"
seed_line=$(grep -n '^## .*Seed the CMS admin' CUTOVER.md | head -1 | cut -d: -f1 || true)
imp_line=$(grep -n '^## .*Import the content' CUTOVER.md | head -1 | cut -d: -f1 || true)
if [[ -n "$seed_line" && -n "$imp_line" && "$seed_line" -lt "$imp_line" ]]; then
  ok "seed BEFORE import — which is the order this wizard runs"
else
  bad "the runbook does not put seed before import any more"
  warn "This wizard seeds first (stage 6) and imports second (stage 7)."
  warn "Read CUTOVER.md and follow it, not this script."
  preflight_failed=1
fi

printf '\n'
if [[ "$preflight_failed" == "1" ]]; then
  warn "Preflight found problems above."
  confirm "Continue anyway?" || stop_here "Preflight failed and you chose to stop."
fi

printf '\n'
say "#40 is blocked by four tickets. Confirm each is actually done — this run"
say "should not be the first time any of it happens:"
step "#38 — CUTOVER.md is corrected. You are about to execute it."
step "#36 — the gated migration workflow exists and its secrets are set."
step "#39 — a deployment exists and was verified on preview."
step "#33 — the rehearsal ran, so the freeze duration is known, not guessed."
printf '\n'
confirm "All four are done?" || stop_here "Blocked by #38 / #36 / #39 / #33."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Confirm the initial course set with Sachi"
say "The course set is an assumption seeded in the import script and — per the"
say "comment above it — has never been confirmed with her. It is far cheaper to"
say "change now than after learners have progress rows against it."
printf '\n'
say "What the import will create (scripts/migrate/01-content-to-payload.ts):"
printf '\n'
note "  Course 1  Hiragana & prefectures      (hiragana-and-prefectures)"
note "              1. hiragana-l1-v1-hokkaido"
note "              2. hiragana-l2-v1-iwate"
note "  Course 2  Grammar & conversation      (grammar-and-conversation)"
note "              1. l1-v1     2. l1-v2     3. l2-v1"
printf '\n'
say "That is the whole live catalogue: 2 courses, 5 lessons, 8 resource groups."
say "\"2 lessons\" in a course is success here, not a partial import (#26)."
printf '\n'
warn "Show her this list before the freeze, not after."
printf '\n'
if confirm "Has Sachi confirmed this course set?"; then
  ok "course set confirmed"
else
  printf '\n'
  say "Change it by editing COURSE_SEED in scripts/migrate/01-content-to-payload.ts"
  say "— it is data on purpose, courses upsert on slug, and lesson order is"
  say "overwritten on every run, so an edited table takes effect cleanly."
  stop_here "The course set is unconfirmed. Ask her, edit COURSE_SEED if needed, re-run."
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Collect the production connection values"
say "Three values, held for this run only. Nothing production-pointing is"
say "written to disk until stage 6, and it is removed again in stage 7."
printf '\n'

PROD_DATABASE_URL=""
if have npm && confirm "Read the pooled production URL from neonctl now?"; then
  say "running: npm run db:branch:url -- production"
  PROD_DATABASE_URL=$(npm run --silent db:branch:url -- production 2>/dev/null | tr -d '\r' | grep -E '^postgres' | tail -1 || true)
  if [[ -n "$PROD_DATABASE_URL" ]]; then
    ok "got $(mask "$PROD_DATABASE_URL")"
  else
    warn "neonctl returned nothing usable — paste it instead"
  fi
fi
while [[ -z "$PROD_DATABASE_URL" ]]; do
  ask_secret PROD_DATABASE_URL "Pooled production DATABASE_URL:"
done
case "$PROD_DATABASE_URL" in
  *-pooler*) ok "pooled connection string (has -pooler)" ;;
  *) warn "that URL has no '-pooler' in the host — it is the direct string."
     confirm "Use it anyway?" || stop_here "Get the pooled URL: npm run db:branch:url -- production" ;;
esac

printf '\n'
say "PAYLOAD_SECRET must be the SAME value as the Vercel env and the repo"
say "secret the migration workflow uses. A different one migrates a database"
say "the app cannot then boot against — /admin and every content page 500."
ask_secret PROD_PAYLOAD_SECRET "PAYLOAD_SECRET (from 1Password):"
[[ -n "$PROD_PAYLOAD_SECRET" ]] || stop_here "PAYLOAD_SECRET is required — the app does not boot without it."

printf '\n'
say "MONGODB_URI must include the /Cornerstone database name. Without it you"
say "silently connect to an empty 'test' database and the import finds nothing."
while true; do
  ask_secret PROD_MONGODB_URI "Production MONGODB_URI (…/Cornerstone):"
  case "${PROD_MONGODB_URI%%\?*}" in
    */Cornerstone|*/Cornerstone/) ok "database name present"; break ;;
    *) bad "no /Cornerstone in the path"
       confirm "Use it anyway (the import will assert this too)?" && break ;;
  esac
done

printf '\n'
say "Finally, the deployment this run must prove itself against — stage 3 of"
say "CUTOVER saved both of these into $ENV_FILE."
ask VERCEL_DEPLOYMENT_URL "Deployment URL (https://….vercel.app):"
ask_secret VERCEL_AUTOMATION_BYPASS_SECRET "Vercel protection bypass secret:"
if [[ -z "$VERCEL_DEPLOYMENT_URL" || -z "$VERCEL_AUTOMATION_BYPASS_SECRET" ]]; then
  SKIPPED+=("Deployment URL / bypass secret missing — the /api/cms_admins/init checks in stages 5 and 6 could not run")
  warn "the bootstrap-window checks will be skipped"
else
  # Persisted, unlike the three above: these belong in .env.local anyway, and
  # keeping them means a re-run after a Ctrl-C does not ask again.
  write_env VERCEL_DEPLOYMENT_URL "$VERCEL_DEPLOYMENT_URL"
  write_env VERCEL_AUTOMATION_BYPASS_SECRET "$VERCEL_AUTOMATION_BYPASS_SECRET"
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Announce the content freeze"
say "From here until Sachi is back in the CMS, anything she writes in Compass"
say "is lost unless stage 7 is re-run. Tell her before you migrate, not after."
printf '\n'
say "The rehearsal (#33) measured the scripts at under a minute in total. What"
say "actually sizes the window is one approval click, and — later — DNS and a"
say "by-hand checklist. So promise an hour and tell her it will probably be less."
printf '\n'
note "Something like:"
note "  Freezing content edits now — please stop editing in Compass until I say"
note "  it's clear. Should be under an hour. When it's done you'll edit lessons"
note "  in the new CMS instead, and I'll send you a login."
printf '\n'
confirm "Freeze announced, with a stated duration?" \
  || stop_here "Announce the freeze first — that is #40's first acceptance criterion."
ok "freeze announced"

printf '\n'
say "Recording the high-water mark, so \"did someone edit through the freeze?\""
say "is a question you can answer rather than guess."
FREEZE_MARK="$RUN_DIR/highwater-freeze.txt"
if highwater "$FREEZE_MARK"; then
  printf '\n'
  cat "$FREEZE_MARK"
  printf '\n'
  ok "saved to $FREEZE_MARK"
else
  bad "mongosh could not read the source collections"
  cat "$FREEZE_MARK"
  SKIPPED+=("Freeze high-water mark was never recorded")
  warn "Stage 7 will not be able to tell whether the source moved."
  confirm "Continue without it?" || stop_here "Fix MONGODB_URI and re-run."
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Migrate the production database — through CI, not this laptop"
say "drizzle first (it creates the payload schema), then Payload. That order is"
say "baked into the workflow, which is one reason it does not run from here."
printf '\n'
if confirm "Dispatch migrate-production.yml now?"; then
  gh workflow run migrate-production.yml || warn "dispatch failed — run it from the Actions tab"
  printf '\n'
  say "It targets the 'production' GitHub Environment, so a required reviewer"
  say "has to approve it. That click is usually the longest part of the freeze."
  open_url "https://github.com/nihongojp/cornerstone/actions/workflows/migrate-production.yml"
  printf '\n'
  step "Approve the run if it is waiting on you."
  step "Watch it to completion (gh run watch, or the browser)."
  pause "Press Enter once the run has finished."
else
  SKIPPED+=("migrate-production.yml was not dispatched from this wizard")
  say "Run it yourself before continuing: gh workflow run migrate-production.yml"
  pause
fi

printf '\n'
say "Verifying against the database itself — the workflow's 'Show pending"
say "migrations' step runs BEFORE the migrations and may error on a missing"
say "payload schema. That is diagnostic output, not a result. This is the result:"
printf '\n'
psql "$PROD_DATABASE_URL" \
  -c '\dt public.*' \
  -c "select conname from pg_constraint where conname = 'user_progress_lesson_id_lessons_slug_fk'" \
  2>&1 | tee "$RUN_DIR/psql-verify.txt" || true
printf '\n'
say "Expect five tables in public — user, session, account, verification,"
say "user_progress — and one constraint row."
printf '\n'
warn "An asymmetric run is normal: drizzle may report nothing to do while"
warn "Payload applies several. What is NOT normal is BOTH finding nothing —"
warn "that means the workflow never reached this database."
printf '\n'
confirm "Five tables and the constraint row are there?" \
  || stop_here "Production is not migrated. Read the workflow log before re-running."
ok "production schema is in place"

if [[ -n "$VERCEL_DEPLOYMENT_URL" && -n "$VERCEL_AUTOMATION_BYPASS_SECRET" ]]; then
  printf '\n'
  say "And the bootstrap window is now genuinely open — cms_admins exists but is"
  say "empty. Checking what the deployment says:"
  init_before=$(init_state)
  note "  /api/cms_admins/init → $init_before"
  case "$init_before" in
    *'"initialized":false'*) ok "as expected before seeding — stage 6 closes this" ;;
    *'"initialized":true'*)  ok "already seeded — stage 6 is idempotent, run it anyway" ;;
    *) warn "unexpected answer. A 401 means the bypass secret is stale or the URL"
       warn "points at a different deployment; a 500 means the deployment's env"
       warn "does not match the migrated database (usually PAYLOAD_SECRET)." ;;
  esac
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Seed the CMS admin accounts — close the bootstrap window"
say "Before the import, deliberately: seeding needs only the database and"
say "PAYLOAD_SECRET, and until one cms_admins row exists Payload offers an"
say "unauthenticated first-user form to anyone who reaches /admin (#32)."
printf '\n'
arm_production_env

say "The committed roster is two people — Justin and Sachi. #40 expects four"
say "accounts, so add anyone else here as 'Name <email>' (blank line to finish)."
note "This is idempotent and identical to adding a ROSTER line later."
printf '\n'
SEED_ARGS=()
while true; do
  printf '  %sExtra admin (Name <email>), or Enter to finish:%s ' "$BOLD" "$RESET"
  read -r extra || true
  [[ -z "$extra" ]] && break
  case "$extra" in
    *\<*@*\>*) SEED_ARGS+=("$extra"); ok "will seed: $extra" ;;
    *) warn "needs the form: Dev <dev@example.com>" ;;
  esac
done

printf '\n'
say "Passwords print exactly once and are stored nowhere. This wizard captures"
say "them to a private file so the next screen-clear cannot lose them — and"
say "deletes that file before moving on."
printf '\n'
umask 077
SEED_CAPTURE="$RUN_DIR/admin-passwords.txt"
set +e
if [[ ${#SEED_ARGS[@]} -gt 0 ]]; then
  npm run --silent payload:seed-admins -- "${SEED_ARGS[@]}" 2>&1 | tee "$SEED_CAPTURE"
else
  npm run --silent payload:seed-admins 2>&1 | tee "$SEED_CAPTURE"
fi
seed_status=${PIPESTATUS[0]}
set -e
printf '\n'
case "$seed_status" in
  0) ok "seeded (or nothing left to do) — existing accounts were left untouched" ;;
  2) bad "exit 2 — bad input, or PAYLOAD_SECRET/DATABASE_URL missing. Nothing was attempted."
     stop_here "Fix the input and re-run; nothing was written." ;;
  *) bad "exit $seed_status — it failed partway."
     warn "Re-running is safe: existing accounts are left alone, down to the hash."
     confirm "Continue anyway?" || stop_here "Seeding failed." ;;
esac

printf '\n'
warn "Deliver every password above through 1Password NOW — this is the only"
warn "copy, and the next screen clears it. Each person changes theirs at first"
warn "sign-in. /admin's 'Forgot password?' silently does nothing (no email"
warn "adapter), so a lost password before first sign-in needs another admin."
printf '\n'
until confirm "Every generated password is in 1Password?"; do
  say "Take the time — the file is $SEED_CAPTURE and it is about to be deleted."
done
shred_capture
ok "capture file deleted"

if [[ -n "$VERCEL_DEPLOYMENT_URL" && -n "$VERCEL_AUTOMATION_BYPASS_SECRET" ]]; then
  printf '\n'
  init_after=$(init_state)
  note "  /api/cms_admins/init → $init_after"
  case "$init_after" in
    *'"initialized":true'*) ok "bootstrap window closed permanently" ;;
    *'"initialized":false'*)
      bad "still open — the seed did not land in the database this deployment reads"
      stop_here "cms_admins is still empty from the app's point of view." ;;
    *) warn "could not read it; parity in CUTOVER step 9 asserts this too"
       SKIPPED+=("/api/cms_admins/init never confirmed initialized:true") ;;
  esac
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Import the content — the round-trip verification is a hard gate"
say "First: did anything move in Mongo since the freeze was announced?"
printf '\n'
IMPORT_MARK="$RUN_DIR/highwater-preimport.txt"
if highwater "$IMPORT_MARK"; then
  if [[ -f "$FREEZE_MARK" ]] && diff -q "$FREEZE_MARK" "$IMPORT_MARK" >/dev/null 2>&1; then
    ok "unchanged since the freeze"
  else
    warn "the source moved since the freeze — someone edited through it:"
    diff "$FREEZE_MARK" "$IMPORT_MARK" || true
    printf '\n'
    note "That is fine: this import picks it up. What is not fine is a move"
    note "AFTER this run — that needs the import re-running."
    pause
  fi
else
  SKIPPED+=("Pre-import high-water mark could not be read")
  warn "could not re-read Mongo; the import itself will fail loudly if it cannot connect"
fi

printf '\n'
say "Running the import. Expected on the way through:"
note "  Source volume     2 legacy lessons, 3 grammar lessons, 8 resource groups"
note "  Grammar items in  l1-v1 18, l1-v2 23, l2-v1 27"
note "  Legacy exercises  hiragana-l1-v1-hokkaido 14, hiragana-l2-v1-iwate 9"
note "  legacyJson        nothing routed to it"
note "  Final tally       2 courses, 5 lessons, 8 resources, 141 exercises"
printf '\n'
note "It is idempotent — lessons upsert on the Mongo _id, courses on slug — so"
note "a doubted run can simply be repeated."
pause "Press Enter to run npm run migrate:content."

IMPORT_LOG="$RUN_DIR/import.log"
printf '\n'
set +e
npm run --silent migrate:content 2>&1 | tee "$IMPORT_LOG"
import_status=${PIPESTATUS[0]}
set -e
printf '\n'

if [[ "$import_status" != "0" ]]; then
  bad "the import exited $import_status"
  say "Read $IMPORT_LOG. Common causes: 'Import finds nothing' is MONGODB_URI"
  say "without /Cornerstone; a stop at 'Source volume' means Mongo moved under"
  say "you and it refused to import a partial set."
  stop_here "The import failed. Do not continue to DNS."
fi

if grep -q 'VERIFICATION PASSED' "$IMPORT_LOG"; then
  ok "round-trip verification passed — stored content reproduces the"
  ok "learner-visible sequence computed from Mongo exactly"
else
  bad "no VERIFICATION PASSED line in the output"
  stop_here "The verification is the only proof the expansion was done correctly."
fi

printf '\n'
say "Final tally it reported:"
printf '\n'
grep -A6 'Final content in Payload' "$IMPORT_LOG" || true
printf '\n'
note "courses and lessons are gated; exercises and blocks are derived totals it"
note "does not check. If exercises differ from 141, the verification block above"
note "is the assertion that matters — not the tally."
printf '\n'
confirm "2 courses and 5 lessons, and the verification passed?" \
  || stop_here "Counts are wrong. Read the verification block in $IMPORT_LOG."

printf '\n'
disarm_production_env
ok "content is in Payload — it is now the source of truth"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Hand the CMS to Sachi"
say "The last acceptance criterion is hers: signed in, and able to author."
printf '\n'
warn "One wrinkle before DNS. Standard Protection covers the *.vercel.app URL,"
warn "so /admin sits behind Vercel's auth wall — she needs a Vercel account on"
warn "the project to reach the Payload login at all. Two honest options:"
printf '\n'
step "a) Invite her to the Vercel project now, and she signs in today."
step "b) Defer her sign-in to just after DNS (CUTOVER step 8), when the custom"
step "   domain is public and the wall no longer applies."
printf '\n'
if confirm "Invite her to Vercel and do it now?"; then
  ask VERCEL_TEAM_SLUG "Vercel team (or account) slug:"
  [[ -n "$VERCEL_TEAM_SLUG" ]] && open_url "https://vercel.com/teams/${VERCEL_TEAM_SLUG}/settings/members"
  step "Invite Sachi's email as a Member."
  step "Send her the /admin URL and her 1Password credential."
  if [[ -n "$VERCEL_DEPLOYMENT_URL" ]]; then
    printf '\n'
    note "  ${VERCEL_DEPLOYMENT_URL%/}/admin"
    printf '\n'
  fi
  step "Ask her to sign in, change her password, and edit one lesson title."
  pause "Press Enter once she has tried."
  if confirm "Sachi signed in and successfully edited content?"; then
    ok "she is authoring again — the outage is over"
  else
    SKIPPED+=("Sachi has not confirmed she can author — #40's last acceptance criterion")
    warn "recorded as outstanding"
  fi
else
  SKIPPED+=("Sachi's admin sign-in deferred until after DNS (CUTOVER step 8) — #40's last acceptance criterion stays open")
  say "Recorded as deferred. Tell her the freeze on Compass still holds and that"
  say "her login arrives with the domain switch."
  pause
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Close out — and confirm you did not touch DNS"
say "Nothing in this run was supposed to change what learners see. Checking:"
printf '\n'
if have dig; then
  dns_now=$(dig +short learn.nihongojp.com 2>/dev/null | tr '\n' ' ' || true)
  note "  learn.nihongojp.com → ${dns_now:-(no answer)}"
  say "That should still be whatever it was before this run — the old stack, or"
  say "nothing at all. Vercel's own records are CUTOVER step 8, not this ticket."
else
  note "dig not available — confirm by eye that DNS is unchanged"
fi
printf '\n'
confirm "DNS is untouched?" || warn "Then this run went further than #40. Read CUTOVER step 8 and Rollback."

printf '\n'
say "#40's acceptance criteria, for the ticket:"
step "freeze announced with a duration"
step "course set confirmed with Sachi"
step "migrations ran through CI, drizzle then Payload"
step "import round-tripped cleanly with the expected counts"
step "cms_admins seeded, passwords delivered out-of-band"
step "Sachi signed in and authored — or recorded above as outstanding"
step "DNS untouched, old stack still serving"
printf '\n'
say "Next, when you are ready: CUTOVER step 8 (DNS) and step 9 (verify"
say "production). The freeze does not end until step 9's checklist passes."
printf '\n'
if have gh && confirm "Post a run summary as a comment on issue #40?"; then
  if gh issue comment 40 --repo nihongojp/cornerstone --body \
"Production data run executed: freeze announced, course set confirmed, migrations applied via \`migrate-production.yml\`, \`cms_admins\` seeded and passwords delivered out-of-band, content imported with the round-trip verification passing. DNS untouched — the old stack is still serving. Run artifacts: \`$RUN_DIR\`."
  then ok "commented on #40"
  else warn "comment failed — post it by hand"
  fi
fi

finish
