#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Every value this wizard captures is CI-only — nothing belongs in a local
# .env. Point ENV_FILE at a non-file so the library never offers a local
# development secret as the default for a production one.
ENV_FILE=/dev/null

REPO="nihongojp/cornerstone"
NEON_PROJECT_ID_DEFAULT="bold-bar-07861256"   # docs/database-workflow.md

# ── Local helpers (authored, not library) ─────────────────────────────────

# ask_with_default KEY "Prompt" DEFAULT — like ask, but Enter takes DEFAULT.
ask_with_default() {
  local key="$1" prompt="$2" default="$3" input
  printf '  %s%s%s %s[Enter = %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$default" "$RESET"
  read -r input || true
  [[ -z "$input" ]] && input="$default"
  printf -v "$key" '%s' "$input"
}

# manual "what" "how" — record something the wizard could not do itself, so it
# lands in the closing summary instead of being silently lost.
manual() {
  SKIPPED+=("$1 — $2")
  warn "$1"
  note "  do it by hand: $2"
}

HAVE_ADMIN=no

banner "Neon CI database workflows — go live (issue #36)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — gh auth and repo admin"
say "The two Neon workflows are written but inert. This wizard gives them"
say "credentials so PRs get their own database and merges migrate production."
printf '\n'

if ! command -v gh >/dev/null 2>&1; then
  warn "gh is not installed — every secret below will have to be set by hand."
  note "  install it: https://cli.github.com"
elif ! gh auth status >/dev/null 2>&1; then
  warn "gh is installed but not authenticated."
  note "  run: gh auth login"
else
  say "gh authenticated as: $(gh api user --jq .login 2>/dev/null || echo unknown)"
  if [[ "$(gh api "repos/$REPO" --jq .permissions.admin 2>/dev/null || echo false)" == "true" ]]; then
    HAVE_ADMIN=yes
    printf '  %s✓%s you have admin on %s — secrets, variables and environments can be set from here.\n' \
      "$GREEN" "$RESET" "$REPO"
  else
    warn "your account is NOT an admin of $REPO."
    note "  Repository secrets, variables and Environments all require admin."
    note "  The wizard will still collect every value and print exactly what to"
    note "  do with it, but you (or a repo admin) will apply them in the UI."
  fi
fi
printf '\n'
say "Run this wizard from the repository root — gh resolves the repo from cwd."
pause "Ready?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Neon — API key"
say "The preview-branch workflow uses this to create and delete a Neon branch"
say "per pull request. It needs access to the whole project, not one branch."
open_url "https://console.neon.tech"
step "Open the user menu (top right) → Account settings → API keys."
step "If the project belongs to an organization, switch to the org first, then"
step "  Settings → API keys — a personal key cannot reach an org project."
step "Click 'Create new API key', name it something like 'github-actions-ci'."
step "Copy the key now — Neon shows it exactly once."
ask_secret NEON_API_KEY "Paste the Neon API key:"
if [[ -n "$NEON_API_KEY" ]]; then
  set_secret NEON_API_KEY "$NEON_API_KEY"
else
  manual "NEON_API_KEY not captured" "gh secret set NEON_API_KEY"
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Neon — project id"
say "This one is public, so it is a GitHub *variable*, not a secret. Both"
say "workflows read it as \${{ vars.NEON_PROJECT_ID }}."
printf '\n'
warn "Setting this ARMS the preview workflow. Both of its jobs are gated on"
warn "vars.NEON_PROJECT_ID != '' — they skip while it is unset, so pull"
warn "requests stay green instead of failing against a database that is not"
warn "configured yet. The gate is on the variable rather than the secret"
warn "because 'secrets' is not available in a job-level 'if'."
note "That is why the API key went first: set the variable before the secret"
note "and the next pull request runs the workflow without a key to use."
printf '\n'
note "docs/database-workflow.md records the project as: $NEON_PROJECT_ID_DEFAULT"
say "If that no longer matches, it is in the Neon console URL:"
say "  console.neon.tech/app/projects/<project-id>"
ask_with_default NEON_PROJECT_ID "Neon project id:" "$NEON_PROJECT_ID_DEFAULT"
set_var NEON_PROJECT_ID "$NEON_PROJECT_ID"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Neon — production connection string"
say "migrate-production applies migrations through this. It must be the POOLED"
say "string for the 'production' branch — not development, not direct."
open_url "https://console.neon.tech/app/projects/$NEON_PROJECT_ID/branches"
step "Select the 'production' branch."
step "In the Connection details panel, make sure the branch is 'production'."
step "Turn ON 'Pooled connection' (the host then contains '-pooler')."
step "Copy the connection string."
warn "Do NOT put this value in .env.local — local dev uses the 'development' branch."
ask_secret PRODUCTION_DATABASE_URL "Paste the pooled production connection string:"
USE_DB_URL=yes
if [[ -z "$PRODUCTION_DATABASE_URL" ]]; then
  USE_DB_URL=no
  manual "PRODUCTION_DATABASE_URL not captured" "gh secret set PRODUCTION_DATABASE_URL"
elif [[ "$PRODUCTION_DATABASE_URL" != *"-pooler."* ]]; then
  warn "that string does not look pooled — a pooled Neon host contains '-pooler'."
  if ! confirm "Use it anyway?"; then
    USE_DB_URL=no
    manual "PRODUCTION_DATABASE_URL not set" \
      "re-run this wizard and copy the string with 'Pooled connection' turned on"
  fi
fi
if [[ "$USE_DB_URL" == yes ]]; then
  set_secret PRODUCTION_DATABASE_URL "$PRODUCTION_DATABASE_URL"
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Payload — PAYLOAD_SECRET"
say "Payload signs admin sessions and password-reset links with this. CI must"
say "use the SAME value as the deployed app, or migrating production from CI"
say "would invalidate every live session."
printf '\n'
if confirm "Is the app already deployed with a PAYLOAD_SECRET set on Vercel?"; then
  open_url "https://vercel.com/dashboard"
  step "Open the Cornerstone project → Settings → Environment Variables."
  step "Find PAYLOAD_SECRET, scoped to Production."
  step "Use the row menu (…) → Copy Value. Reveal it first if it is hidden."
  ask_secret PAYLOAD_SECRET "Paste PAYLOAD_SECRET:"
else
  say "Nothing deployed yet — generate one now and use it in both places."
  PAYLOAD_SECRET="$(openssl rand -base64 32)"
  printf '  %s✓ generated%s PAYLOAD_SECRET:\n\n    %s\n\n' "$GREEN" "$RESET" "$PAYLOAD_SECRET"
  warn "Copy that value into Vercel's Production environment as PAYLOAD_SECRET"
  warn "as well — the app and CI must agree."
  manual "PAYLOAD_SECRET on Vercel" "add it to the Vercel project's Production env vars"
  pause "Copied it? Press Enter."
fi
if [[ -n "${PAYLOAD_SECRET:-}" ]]; then
  set_secret PAYLOAD_SECRET "$PAYLOAD_SECRET"
else
  manual "PAYLOAD_SECRET not captured" "gh secret set PAYLOAD_SECRET"
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Auth — BETTER_AUTH_SECRET"
say "Only the preview workflow needs this: 'npm run build' refuses to boot"
say "without it. It never touches production data, but keeping it equal to the"
say "deployed value keeps the preview build faithful."
printf '\n'
if confirm "Is BETTER_AUTH_SECRET already set on Vercel?"; then
  open_url "https://vercel.com/dashboard"
  step "Cornerstone project → Settings → Environment Variables."
  step "Find BETTER_AUTH_SECRET (Production) → (…) → Copy Value."
  ask_secret BETTER_AUTH_SECRET "Paste BETTER_AUTH_SECRET:"
else
  BETTER_AUTH_SECRET="$(openssl rand -base64 32)"
  printf '  %s✓ generated%s BETTER_AUTH_SECRET:\n\n    %s\n\n' "$GREEN" "$RESET" "$BETTER_AUTH_SECRET"
  warn "Set this same value on Vercel too, or deployed sessions will not match."
  manual "BETTER_AUTH_SECRET on Vercel" "add it to the Vercel project's Production env vars"
  pause "Copied it? Press Enter."
fi
if [[ -n "${BETTER_AUTH_SECRET:-}" ]]; then
  set_secret BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"
else
  manual "BETTER_AUTH_SECRET not captured" "gh secret set BETTER_AUTH_SECRET"
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Neon — protect the production branch"
say "Protection is what makes 'only the workflow writes to production' a rule"
say "the system enforces rather than a convention someone remembers. It blocks"
say "deletion and can restrict which connections are allowed."
note "This is a Neon paid-plan feature (Launch: up to 2 protected branches)."
open_url "https://console.neon.tech/app/projects/$NEON_PROJECT_ID/branches"
step "Select the 'production' branch."
step "On the branch page, click 'Protect'."
step "In the 'Set as protected' dialog, click 'Set as protected' to confirm."
printf '\n'
if confirm "Is 'production' now marked protected?"; then
  printf '  %s✓%s production branch protected\n' "$GREEN" "$RESET"
else
  manual "Neon 'production' branch is not protected" \
    "Neon console → Branches → production → Protect (needs a paid plan)"
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "GitHub — the 'production' Environment"
say "migrate-production runs with 'environment: production'. The environment"
say "must exist, and whether it requires a human reviewer is a decision issue"
say "#36 asks you to make deliberately — either way, but on purpose."
printf '\n'
say "  With a reviewer:    every production migration waits for an explicit"
say "                      approval in the Actions UI before it touches the DB."
say "  Without a reviewer: merging the PR is the approval; migrations apply as"
say "                      soon as the push lands."
printf '\n'

REVIEWER_PAYLOAD='{}'
REVIEWER_CHOICE="no reviewer — merging is the approval"
if confirm "Require a human reviewer before production migrations?"; then
  ask_with_default REVIEWER_LOGIN "GitHub login of the required reviewer:" \
    "$(gh api user --jq .login 2>/dev/null || echo '')"
  if [[ -n "$REVIEWER_LOGIN" ]]; then
    REVIEWER_ID=$(gh api "users/$REVIEWER_LOGIN" --jq .id 2>/dev/null || true)
    if [[ -n "$REVIEWER_ID" ]]; then
      REVIEWER_PAYLOAD=$(printf '{"reviewers":[{"type":"User","id":%s}]}' "$REVIEWER_ID")
      REVIEWER_CHOICE="required reviewer: $REVIEWER_LOGIN"
    else
      warn "could not resolve GitHub user '$REVIEWER_LOGIN' — creating the"
      warn "environment without a reviewer; add one in the UI."
      manual "required reviewer on the production environment" \
        "Settings → Environments → production → Required reviewers"
    fi
  fi
fi

if [[ "$HAVE_ADMIN" == "yes" ]]; then
  if printf '%s' "$REVIEWER_PAYLOAD" \
      | gh api -X PUT "repos/$REPO/environments/production" --input - >/dev/null 2>&1; then
    printf '  %s✓%s environment "production" configured (%s)\n' "$GREEN" "$RESET" "$REVIEWER_CHOICE"
  else
    manual "production environment not created" \
      "Settings → Environments → New environment → production ($REVIEWER_CHOICE)"
  fi
else
  manual "production environment not created (needs repo admin)" \
    "Settings → Environments → New environment → production ($REVIEWER_CHOICE)"
fi
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Verify — dispatch migrate-production"
say "This proves the credentials work. The workflow prints pending Payload"
say "migrations BEFORE it applies anything, so the status step is the real"
say "check; if it reports nothing pending, applying is a no-op."
printf '\n'
if [[ "${REVIEWER_CHOICE}" == required* ]]; then
  warn "You set a required reviewer, so the run will pause for approval —"
  warn "approve it in the Actions UI when prompted."
fi
printf '\n'
if confirm "Dispatch 'Migrate production database' now?"; then
  if gh workflow run migrate-production.yml >/dev/null 2>&1; then
    printf '  %s✓%s dispatched — watching the run\n\n' "$GREEN" "$RESET"
    sleep 5
    gh run watch "$(gh run list --workflow=migrate-production.yml --limit 1 --json databaseId --jq '.[0].databaseId')" \
      || warn "watch ended early — check: gh run list --workflow=migrate-production.yml"
  else
    manual "migrate-production was not dispatched" \
      "gh workflow run migrate-production.yml"
  fi
else
  manual "migrate-production not verified" "gh workflow run migrate-production.yml"
fi
pause

finish

note "Next: open a pull request. It should create a preview/pr-<n> Neon branch,"
note "run both migration systems in order, typecheck and build — then delete the"
note "branch when the PR closes. Watch it with: gh run list --workflow=neon-preview-branch.yml"
printf '\n'
